### ISSUE TITLE
[Query][tflite]The tool or cmdline to support NCHW between NHWC

### ISSUE THREAD

**Issue by joyoki** [PINTO0309/onnx2tf#10]
### Issue Type

Others

### onnx2tf version number

1.0.48

### Download URL for ONNX

Model:
1.[face_recognition_sface_2021dec.onnx](https://github.com/opencv/opencv_zoo/blob/master/models/face_recognition_sface/face_recognition_sface_2021dec.onnx)
2.https://github.com/opencv/opencv_zoo/blob/master/models/face_recognition_sface/face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx

### Parameter Replacement JSON

```json
NA
```

### Description

Hi  @PINTO0309 
Thanks for your job and it working when  ONNX covert to tflite without quantizion.
for quantized ONNX model or tflite model, the tool seems not working for belwo error
`Bad node spec for node. Name: _mulscalar0_quant OpType: QLinearMul`

so i would like to check with you
whether the tool   support NCHW between NHWC  convertion for tflite model?

Thanks

**Comment by PINTO0309** [comment]
It is still under development. I am in the process of implementing `DequantizeLinear` as hard as I can.
![image](https://user-images.githubusercontent.com/33194443/199671969-c7a4f657-bebe-4785-8d60-eacd886e9b63.png)
![image](https://user-images.githubusercontent.com/33194443/199672060-2b76f39e-ee03-430e-aeb7-9ba03627a35a.png)

I have something I would like you to tell me to motivate me.
Why bother converting INT8 quantized models? If I may, I would like to know your motivation.

**Comment by joyoki** [comment]
Hi @PINTO0309 
    Thanks for your quick confirm.
    actually, I would like to compare the model result bettween face_recognition_sface_2021dec.onnx and face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx. while quantized function is not working before v1.048. the quantized model face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx could not convert to .tflite filetype.

that's why i would like to know if had cmdline to convert NCHW to NHWC for tflite when I face question when quantied onnx to tflite

Thanks

**Comment by PINTO0309** [comment]
Thanks.
I am working on an implementation of the `Qxxx` OP around quantization, I just started looking into implementing it about an hour ago so it will still take a few more days.

**Comment by joyoki** [comment]
Good Job， waiting for your good news!

**Comment by PINTO0309** [comment]
Ref: https://github.com/PINTO0309/onnx2tf/commit/247ed0120064b586c27e44b06284dfe067ac21dc

**Comment by joyoki** [comment]
> Ref: [247ed01](https://github.com/PINTO0309/onnx2tf/commit/247ed0120064b586c27e44b06284dfe067ac21dc) [69cd24b](https://github.com/PINTO0309/onnx2tf/commit/69cd24b9a34811d9aa44e6809acd58e2301d3390) [efc49e1](https://github.com/PINTO0309/onnx2tf/commit/efc49e1e60e4fd11b5f78bfa72f866eac24517b5) [8954da0](https://github.com/PINTO0309/onnx2tf/commit/8954da065c3674e137a5d5961f448a4fc86523f6) Note: A large number of non-standard OP opsets for ONNX have been incorporated.
> 
> ```
> com.microsoft v1
> com.microsoft.nchwc v1
> ai.onnx.training v1
> ai.onnx.preview.training v1
> com.microsoft.experimental v1
> ```
> 
> ![image](https://user-images.githubusercontent.com/33194443/199749925-05a0f237-75d2-4ecf-8434-3d918241a3ce.png)

Thanks for your good job first.
I saw you already release V1.1.6.   I had update with the latest version
I had try the V1.1.6, seems the error of "ERROR: QLinearMul OP is not yet implemented."

keep your moving. Good news is worh of waiting.

**Comment by PINTO0309** [comment]
Only a very limited number of OPs can be reverse-quantified. No check is made to ensure that the output is correct or that no accuracy degradation has occurred.

- https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.7
- [model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/9943099/model_float32.tflite.zip)

**Comment by joyoki** [comment]
> Only a very limited number of OPs can be reverse-quantified. No check is made to ensure that the output is correct or that no accuracy degradation has occurred.
> 
> * https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.7
> * https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.8
> * https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.9
> * https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.10
> * https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.11
> * https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.12
> * [model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/9943099/model_float32.tflite.zip)

I had checked and verified the tflite file：[model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/9943099/model_float32.tflite.zip). it works in the APK. could you help share the convertion cmdline for face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx?

Thanks a lot

**Comment by PINTO0309** [comment]
In the process of adding more functionality than was desired, it seemed that another bug had been embedded, so it has been fixed. Simply upgrade to the latest version and convert using the following command.
```
pip install onnx2tf -U
onnx2tf -i face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx
```

**Comment by joyoki** [comment]
> onnx2tf -i face_recognition_sface_2021dec-act_int8-wt_int8-quantized.onnx



Yes, it works now after upgraded to V1.1.13
I come across the bug as you said which i am not sure, so I didn't post .:

```
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/rsi/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 261, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/rsi/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 336, in inverted_operation_enable_disable_wrapper_func
    onnx_node_output_shape = [None if s is not None and not isinstance(s, str) and s < 1 else s for s in onnx_node_output_shape]
TypeError: 'NoneType' object is not iterable
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
```

Thanks again

**Comment by PINTO0309** [comment]
Yes, I am aware of that. That is exactly the part of the new bug you have created by adding a different conversion feature than the one you were hoping for. I have fixed that bug.
