### ISSUE TITLE
[YOLOX] Abort onnxruntime when `keepdims=False` in `ReduceXX` and the final tensor dimension is reduced to zero

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#108]
### Issue Type

Others

### onnx2tf version number

1.5.0

### onnx version number

1.13.0

### tensorflow version number

2.10.0

### Download URL for ONNX

YOLOX-X
https://drive.google.com/file/d/1QQLf83JwLI_EoQFU5xOGKUvtFPsFSWCN/view

### Parameter Replacement JSON

```json
N/A
```

### Description

Ref issue: [[YoloX] output differs between onnx and tflite #107](https://github.com/PINTO0309/onnx2tf/issues/107)

Problems that can occur in most use cases, such as when post-processing results in zero cases. This is not an onnx2tf problem, but rather an onnxruntime specification problem.
![image](https://user-images.githubusercontent.com/33194443/211470894-baf80b0d-bb72-4f6d-947e-d5f9948dd7ad.png)

```
ONNX and TF output value validation started =========================================
INFO: validation_conditions: np.allclose(onnx_outputs, tf_outputs, rtol=1e-05, atol=1e-05, equal_nan=True)
2023-01-10 14:18:07.353720422 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running ReduceMax node. Name:'ReduceMax_686' Status Message: /home/b920405/work/onnxruntime/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:763 void onnxruntime::ValidateKeepDims(const onnxruntime::TensorShape&, int64_t) keepdims was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,4}

[E] No function: __iter__ registered for opset: 11
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/b920405/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/b920405/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/b920405/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/b920405/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/b920405/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/b920405/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/b920405/git/onnx2tf/onnx2tf/onnx2tf.py", line 1521, in <module>
    main()
  File "/home/b920405/git/onnx2tf/onnx2tf/onnx2tf.py", line 1475, in main
    model = convert(
  File "/home/b920405/git/onnx2tf/onnx2tf/onnx2tf.py", line 974, in convert
    dummy_onnx_outputs: List[np.ndarray] = dummy_onnx_inference(
  File "/home/b920405/git/onnx2tf/onnx2tf/utils/common_functions.py", line 2832, in dummy_onnx_inference
    outputs = onnx_session.run(None, dummy_datas)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running ReduceMax node. Name:'ReduceMax_686' Status Message: /home/b920405/work/onnxruntime/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:763 void onnxruntime::ValidateKeepDims(const onnxruntime::TensorShape&, int64_t) keepdims was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,4}
```

1. If `keepdims=False`, modify as follows to slice the corresponding dimension after performing `ReduceXX` with `keepdims=True` and keeping the dimension. https://github.com/PINTO0309/PINTO_model_zoo/blob/efe3e8da69e1ef14014430b1c88c790976ec10ef/342_ALIKE/PINTO_special/make_mnn_matcher.py#L23-L24
2. Make the image `np.ndarray` be input as dummy data when `--check_onnx_tf_outputs_elementwise_close` is executed. sample: https://github.com/PINTO0309/onnx2tf/releases/download/1.0.49/calibration_image_sample_data_20x128x128x3_float32.npy

**Comment by Hyunseok-Kim0** [comment]
I think this happens because dummy input has inappropriate value like all 1's. It worked when I used sample image instead of random value.

**Comment by PINTO0309** [comment]
You are right. However, for special models other than object detection, it is necessary to deal with the runtime Abort in all processes of ReducdXX and ArgXXX.

I found a problem 2 days ago with this ALIKE model.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/342_ALIKE/demo

**Comment by PINTO0309** [comment]
I have not explained it well enough, but I am assuming only a very specific model optimization pattern.

ONNX -> TFLite -> ONNX

**Comment by PINTO0309** [comment]
Successfully implemented and slice correctly, but runtime error in Squeeze when regenerating onnx using tensorflow-onnx. Therefore, improvement is stopped.
![image](https://user-images.githubusercontent.com/33194443/212096284-1ff4e6cd-c2f8-42cb-bc56-d6ed4a0d2730.png)
```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'model/tf.strided_slice_10/StridedSlice__724' Status Message: /home/b920405/work/onnxruntime/onnxruntime/core/providers/cpu/tensor/squeeze.h:52 static onnxruntime::TensorShapeVector onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const TensorShapeVector&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,1}
```
