### ISSUE TITLE
[MobileBERT] RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#130]
### Issue Type

Others

### onnx2tf version number

1.5.16

### onnx version number

1.13.0

### tensorflow version number

2.10.0

### Download URL for ONNX

- tflite
  https://tfhub.dev/tensorflow/lite-model/mobilebert/1/metadata/1?lite-format=tflite

- tflite to onnx
  ```bash
  python -m tf2onnx.convert \
  --opset 11 \
  --tflite lite-model_mobilebert_1_metadata_1.tflite \
  --output lite_model_mobilebert_1_metadata_1.onnx
  
  onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
  onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
  onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
  onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
  onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
  ```

- onnx to tflite
  ```
  onnx2tf -i lite_model_mobilebert_1_metadata_1.onnx -cotof -cotoa 1e-1 -cgdc
  ```

### Parameter Replacement JSON

```json
N/A
```

### Description

The model structure was too complex and overflowed python's `Maximum Recursion Depth`.
The following must be added to the code to avoid this.
```
sys.setrecursionlimit(10000)
```

1. Personal
2. Error
    ```
    Traceback (most recent call last):
      File "/home/b920405/.local/bin/onnx2tf", line 33, in <module>
        sys.exit(load_entry_point('onnx2tf', 'console_scripts', 'onnx2tf')())
      File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 1698, in main
        model = convert(
      File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 718, in convert
        model = tf.keras.Model(inputs=inputs, outputs=outputs)
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
        result = method(self, *args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 165, in __init__
        self._init_graph_network(inputs, outputs)
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
        result = method(self, *args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 264, in _init_graph_network
        nodes, nodes_by_depth, layers, _ = _map_graph_network(
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 1046, in _map_graph_network
        nodes_in_decreasing_depth, layer_indices = _build_map(outputs)
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 1176, in _build_map
        _build_map_helper(
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 1219, in _build_map_helper
        _build_map_helper(
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 1219, in _build_map_helper
        _build_map_helper(
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 1219, in _build_map_helper
        _build_map_helper(
      [Previous line repeated 986 more times]
      File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 1199, in _build_map_helper
        node = layer._inbound_nodes[node_index]
    RecursionError: maximum recursion depth exceeded
    ```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.5.17

**Comment by PINTO0309** [comment]
Ref: https://github.com/tensorflow/tensorflow/issues/59232
