### ISSUE TITLE
Failed to convert yolox.onnx to int16 activations tflite with 'per-tensor'

### ISSUE THREAD

**Issue by fangliang425** [PINTO0309/onnx2tf#192]
### Issue Type

Others

### onnx2tf version number

1.6.7

### onnx version number

1.13.0

### tensorflow version number

2.10.0

### Download URL for ONNX

yolox_nano_416x416.onnx downloaded from https://raw.githubusercontent.com/PINTO0309/PINTO_model_zoo/main/132_YOLOX/download_nano.sh

### Parameter Replacement JSON

```json
{}
```

### Description

1. Personal project
2. I was trying to convert the yolox_nano_416x416.onnx to Full INT8 Quantization with int16 activations tflite with '-qt per-tensor', here is the command I ran `onnx2tf -i yolox_nano_416x416.onnx -oiqt -qt per-tensor`, but got the errors

> Traceback (most recent call last):
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/onnx2tf/onnx2tf.py", line 1097, in convert
    tflite_model = converter.convert()
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1863, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 930, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1512, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1138, in convert
    return self._optimize_tflite_model(
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 868, in _optimize_tflite_model
    model = self._quantize(model, q_in_type, q_out_type, q_activations_type,
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 627, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/liang/anaconda3/envs/python38/lib/python3.8/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 176, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

3. It works with the default 'per-channel' `onnx2tf -i yolox_nano_416x416.onnx -oiqt`, so there might be something wrong with the per-tensor quantized model.
4. We need a per-tensor quantized tflite model that can run on edge_tpu embeded camera.
5. None

**Comment by PINTO0309** [comment]
It generates `yolox_nano_416x416_full_integer_quant.tflite` but I don't see what the problem is for you. Will your TPU embedded camera work with the INT16 activation model? My understanding is that TPU is not compatible with anything other than INT8, am I wrong?
```
onnx2tf -i yolox_nano_416x416.onnx -oiqt -qt per-tensor

:
saved_model output complete!
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Float32 tflite output complete!
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Float16 tflite output complete!
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Dynamic Range Quantization tflite output complete!
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
INT8 Quantization tflite output complete!
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Full INT8 Quantization tflite output complete!
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 1110, in convert
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1863, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 930, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1512, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1138, in convert
    return self._optimize_tflite_model(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 868, in _optimize_tflite_model
    model = self._quantize(model, q_in_type, q_out_type, q_activations_type,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 627, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/optimize/calibrator.py", line 176, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.
WARNING: INT8 Quantization with int16 activations tflite output failed.
Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 1144, in convert
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1863, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 930, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1512, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1138, in convert
    return self._optimize_tflite_model(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 868, in _optimize_tflite_model
    model = self._quantize(model, q_in_type, q_out_type, q_activations_type,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 627, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/optimize/calibrator.py", line 176, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.
WARNING: Full INT8 Quantization with int16 activations tflite output failed.
```
`yolox_nano_416x416_full_integer_quant.tflite`
![image](https://user-images.githubusercontent.com/33194443/219621890-ea5bd232-39ae-476f-af48-e47cd240e7fc.png)
![image](https://user-images.githubusercontent.com/33194443/219622819-20202220-3f4c-4bf7-a1f1-d682520b0d5b.png)

**Comment by fangliang425** [comment]
Thanks for quick reply, my fault didn't make it clear. 
Yes, the camera works with the per-tensor INT8 tflite, while I found the the failure of converting to INT16 activation model during the conversion. So I was just curious why it failed.

Thanks again for the great work.

**Comment by PINTO0309** [comment]
At the moment, INT16 is a very experimental implementation and does not appear to be taken seriously.
https://www.tensorflow.org/lite/performance/model_optimization
