### ISSUE TITLE
[EleGANt] [GridSample] tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer 'tf.reshape_33' (type TFOpLambda)

### ISSUE THREAD

**Issue by TomatoBoy90** [PINTO0309/onnx2tf#213]
### Issue Type

Feature Request

### onnx2tf version number

1.7.8

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc0

### Download URL for ONNX

https://drive.google.com/file/d/1U9Z4clHqBogdM99LKtsZrWqvMW32D7PG/view?usp=sharing

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "Reshape_416",
      "param_target": "outputs",
      "param_name": "onnx::Clip_459",
      "post_process_transpose_perm": [0,2,3,1]
    }
  ]
}
```

### Description

Hello thank you very much for maintaining this library, but I encountered some problems in the process of using it, and the detailed results are as follows:
```
INFO: onnx_op_type: Reshape onnx_op_name: Reshape_416
INFO:  input_name.1: onnx::Reshape_447 shape: [1, 16384, 2] dtype: float32
INFO:  input_name.2: onnx::Reshape_2844 shape: [4] dtype: <class 'numpy.int64'>
INFO:  output_name.1: onnx::Clip_459 shape: [1, 128, 128, 2] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 279, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 357, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 48, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/onnx2tf/ops/Reshape.py", line 209, in make_node
    tf_partial_model_result_infos: Dict[Any] = dummy_tf_inference(
  File "//AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 3010, in dummy_tf_inference
    outputs = model(
  File "AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer 'tf.reshape_33' (type TFOpLambda).

{{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 536870912 values, but the requested shape has 32768 [Op:Reshape]

Call arguments received by layer 'tf.reshape_33' (type TFOpLambda):
  • tensor=tf.Tensor(shape=(16384, 16384, 2), dtype=float32)
  • shape=['1', '128', '128', '2']
  • name=None
ERROR: input_onnx_file_path: model_grid_sample.onnx
ERROR: onnx_op_name: Reshape_416
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option
```

![image](https://user-images.githubusercontent.com/40761785/221849145-e87fc5a8-f3ca-40e7-8271-883ff1a3fb40.png)

**Comment by PINTO0309** [comment]
Bug fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.7.10

**Comment by TomatoBoy90** [comment]
> 

Ok, thank you very much, I have solved the previous bug on my side, and now I am modifying GridSample
![image](https://user-images.githubusercontent.com/40761785/222031713-3d1528d5-594e-4746-8f4b-a83e5cbcc45e.png)

**Comment by TomatoBoy90** [comment]
When I modified the GridSample, I encountered a new problem with the onnx file address as follows:
[](https://drive.google.com/file/d/17eg3-Aw15kFOV4ponnjqZ1MhRsTJ00rs/view?usp=sharing)

```
INFO: onnx_op_type: Mul onnx_op_name: Mul_2178
INFO:  input_name.1: onnx::Mul_2778 shape: [1, 128, 64, 64] dtype: float32
INFO:  input_name.2: onnx::Mul_2780 shape: [1, 128, 64, 64] dtype: float32
INFO:  output_name.1: input.239 shape: [1, 128, 64, 64] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/onnx2tf-1.7.10/onnx2tf/utils/common_functions.py", line 279, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/onnx2tf-1.7.10/onnx2tf/utils/common_functions.py", line 357, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/onnx2tf-1.7.10/onnx2tf/utils/common_functions.py", line 48, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/onnx2tf-1.7.10/onnx2tf/ops/Mul.py", line 184, in make_node
    tf.math.multiply(
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/AN/envs/python_3.10.8_pytorch/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.math.multiply_222" (type TFOpLambda).

Dimensions must be equal, but are 64 and 128 for '{{node tf.math.multiply_222/Mul}} = Mul[T=DT_FLOAT](Placeholder, Placeholder_1)' with input shapes: [1,64,64,128], [1,128,64,64].

Call arguments received by layer "tf.math.multiply_222" (type TFOpLambda):
  ? x=tf.Tensor(shape=(1, 64, 64, 128), dtype=float32)
  ? y=tf.Tensor(shape=(1, 128, 64, 64), dtype=float32)
  ? name='Mul_2178'
ERROR: input_onnx_file_path: model_70_2023_0220_32_2_1_grid_sample_bilinear_sim.onnx
ERROR: onnx_op_name: Mul_2178
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

**Comment by TomatoBoy90** [comment]
I also tried to use replace.json for this, but it doesn't seem to work
```
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "Mul_2178",
      "param_target": "outputs",
      "param_name": "input.239",
      "post_process_transpose_perm": [0,2,3,1]
    }
  ]
}
```

**Comment by PINTO0309** [comment]
I would like to know if there is an official name for this model.

**Comment by TomatoBoy90** [comment]
> I would like to know if there is an official name for this model.



[> I would like to know if there is an official name for this model.](https://github.com/Chenyu-Yang-2000/EleGANt)

**Comment by PINTO0309** [comment]
- replace_EleGANt.json
  ```json
  {
    "format_version": 1,
    "operations": [
      {
        "op_name": "Reshape_2155",
        "param_target": "outputs",
        "param_name": "onnx::Add_2758",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "Slice_2034",
        "param_target": "outputs",
        "param_name": "onnx::Add_2569",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "Add_2036",
        "param_target": "outputs",
        "param_name": "onnx::Add_2571",
        "post_process_transpose_perm": [0,2,3,1]
      }
    ]
  }
  ```

- command
  ```
  onnx2tf \
  -i model_70_2023_0220_32_2_1_grid_sample_bilinear_sim.onnx \
  -prf replace_EleGANt.json \
  -cotof \
  -cotoa 1e-1
  ```

- result
  ![image](https://user-images.githubusercontent.com/33194443/222041228-dec45d6e-0294-46e8-ad4b-770102e8bddd.png)

The conversion was successful, but there seems to be an accuracy error due to a conversion error somewhere. Check the logs, visually identify for yourself where the accuracy error is greatest, and try adjusting the JSON file. 

Since this tool is modified gradually in my personal time, I cannot devote time to detailed research during the day. I am unable at this time to determine if it is a simple transposition error or a bug in the tool.

Your cooperation is appreciated.

**Comment by PINTO0309** [comment]
This tool sometimes makes the wrong decision.

https://github.com/PINTO0309/onnx2tf/issues/133

**Comment by TomatoBoy90** [comment]
Well, thank you very much for solving my bug in your busy daytime, and I would be very happy if you can find time to solve it in the evening!

**Comment by TomatoBoy90** [comment]
The problem has been completely resolved

**Comment by TomatoBoy90** [comment]
The problem has been completely resolved
