### ISSUE TITLE
[IGEV] `AvgPool` aborts under `kernel_shape = [1, 2]`, `strides = [1,2]`, `input = [3840,1,1,80]` conditions.

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#267]
### Issue Type

Others

### onnx2tf version number

1.8.1

### onnx version number

1.13.1

### tensorflow version number

2.12.0

### Download URL for ONNX

https://s3.ap-northeast-2.wasabisys.com/temp-models/onnx2tf_267/igev_sceneflow_192x320.onnx

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/Einsum",
      "param_target": "inputs",
      "param_name": "/desc/Conv_output_0",
      "pre_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Einsum",
      "param_target": "inputs",
      "param_name": "/desc_1/Conv_output_0",
      "pre_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Einsum",
      "param_target": "outputs",
      "param_name": "/Einsum_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    }
  ]
}
```

### Description

1. Personal
2. `AvgPool` aborts under `kernel_shape = [1, 2]`, `strides = [1,2]`, `input = [3840,1,1,80]` conditions.
    ```
    INFO: onnx_op_type: AveragePool onnx_op_name: /AveragePool_1
    INFO:  input_name.1: /Reshape_100_output_0 shape: [3840, 1, 1, 80] dtype: float32
    INFO:  output_name.1: /AveragePool_1_output_0 shape: [3840, 1, 1, 40] dtype: float32
    ERROR: The trace log is below.
    Traceback (most recent call last):
      File "/home/xxxx/git/onnx2tf/onnx2tf/utils/common_functions.py", line 280, in print_wrapper_func
        result = func(*args, **kwargs)
      File "/home/xxxx/git/onnx2tf/onnx2tf/utils/common_functions.py", line 358, in inverted_operation_enable_disable_wrapper_func
        result = func(*args, **kwargs)
      File "/home/xxxx/git/onnx2tf/onnx2tf/utils/common_functions.py", line 49, in get_replacement_parameter_wrapper_func
        func(*args, **kwargs)
      File "/home/xxxx/git/onnx2tf/onnx2tf/ops/AveragePool.py", line 265, in make_node
        pooled_tensor = AveragePooling2D(
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1044, in __call__
        outputs = call_fn(inputs, *args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/layers/pooling.py", line 358, in call
        outputs = self.pool_function(
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
        raise e.with_traceback(filtered_tb) from None
      File "/usr/local/lib/python3.8/dist-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
        return TFOpLambda(op)(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    ValueError: Exception encountered when calling layer "tf.compat.v1.nn.avg_pool_3" (type TFOpLambda).
    
    Negative dimension size caused by subtracting 2 from 1 for '{{node tf.compat.v1.nn.avg_pool_3/AvgPool}} = AvgPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 2, 1], padding="VALID", strides=[1, 1, 2, 1]](Placeholder)' with input shapes: [3840,1,1,80].
    
    Call arguments received by layer "tf.compat.v1.nn.avg_pool_3" (type TFOpLambda):
      • value=tf.Tensor(shape=(3840, 1, 1, 80), dtype=float32)
      • ksize=('1', '1', '2', '1')
      • strides=('1', '1', '2', '1')
      • padding='VALID'
      • data_format='NHWC'
      • name=None
      • input=None
    ERROR: input_onnx_file_path: ../igev_sceneflow_192x320.onnx
    ERROR: onnx_op_name: /AveragePool_1
    ```

**Comment by Hyunseok-Kim0** [comment]
It was possible to convert the model using replacement json below. However, inference using converted tflite failed due to weird problem. I think this is also related with issue #274 since this model also contains GridSample. I had to insert post_process_transpose_perm in front of every GridSample because axis order of tensor was not appropriate.

![Screenshot from 2023-03-31 15-11-20](https://user-images.githubusercontent.com/34959032/229038573-6147b256-a15b-4cb2-a911-701b6df6c706.png)


```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/Einsum",
      "param_target": "inputs",
      "param_name": "/desc/Conv_output_0",
      "pre_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Einsum",
      "param_target": "inputs",
      "param_name": "/desc_1/Conv_output_0",
      "pre_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Einsum",
      "param_target": "outputs",
      "param_name": "/Einsum_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/Reshape_99",
      "param_target": "outputs",
      "param_name": "/Reshape_99_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/Reshape_100",
      "param_target": "outputs",
      "param_name": "/Reshape_100_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/Concat_98",
      "param_target": "outputs",
      "param_name": "/Concat_98_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_99",
      "param_target": "outputs",
      "param_name": "/Concat_99_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_102",
      "param_target": "outputs",
      "param_name": "/Concat_102_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_104",
      "param_target": "outputs",
      "param_name": "/Concat_104_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_109",
      "param_target": "outputs",
      "param_name": "/Concat_109_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_111",
      "param_target": "outputs",
      "param_name": "/Concat_111_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_113",
      "param_target": "outputs",
      "param_name": "/Concat_113_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_115",
      "param_target": "outputs",
      "param_name": "/Concat_115_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_120",
      "param_target": "outputs",
      "param_name": "/Concat_120_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_122",
      "param_target": "outputs",
      "param_name": "/Concat_122_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_124",
      "param_target": "outputs",
      "param_name": "/Concat_124_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_126",
      "param_target": "outputs",
      "param_name": "/Concat_126_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_131",
      "param_target": "outputs",
      "param_name": "/Concat_131_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_133",
      "param_target": "outputs",
      "param_name": "/Concat_133_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_135",
      "param_target": "outputs",
      "param_name": "/Concat_135_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_137",
      "param_target": "outputs",
      "param_name": "/Concat_137_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_142",
      "param_target": "outputs",
      "param_name": "/Concat_142_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_144",
      "param_target": "outputs",
      "param_name": "/Concat_144_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_146",
      "param_target": "outputs",
      "param_name": "/Concat_146_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_148",
      "param_target": "outputs",
      "param_name": "/Concat_148_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_153",
      "param_target": "outputs",
      "param_name": "/Concat_153_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_155",
      "param_target": "outputs",
      "param_name": "/Concat_155_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_157",
      "param_target": "outputs",
      "param_name": "/Concat_157_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_159",
      "param_target": "outputs",
      "param_name": "/Concat_159_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_164",
      "param_target": "outputs",
      "param_name": "/Concat_164_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_166",
      "param_target": "outputs",
      "param_name": "/Concat_166_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_168",
      "param_target": "outputs",
      "param_name": "/Concat_168_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_170",
      "param_target": "outputs",
      "param_name": "/Concat_170_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_175",
      "param_target": "outputs",
      "param_name": "/Concat_175_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_177",
      "param_target": "outputs",
      "param_name": "/Concat_177_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_179",
      "param_target": "outputs",
      "param_name": "/Concat_179_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_181",
      "param_target": "outputs",
      "param_name": "/Concat_181_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_186",
      "param_target": "outputs",
      "param_name": "/Concat_186_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_188",
      "param_target": "outputs",
      "param_name": "/Concat_188_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_190",
      "param_target": "outputs",
      "param_name": "/Concat_190_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_192",
      "param_target": "outputs",
      "param_name": "/Concat_192_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_197",
      "param_target": "outputs",
      "param_name": "/Concat_197_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_199",
      "param_target": "outputs",
      "param_name": "/Concat_199_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_201",
      "param_target": "outputs",
      "param_name": "/Concat_201_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_203",
      "param_target": "outputs",
      "param_name": "/Concat_203_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_208",
      "param_target": "outputs",
      "param_name": "/Concat_208_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_210",
      "param_target": "outputs",
      "param_name": "/Concat_210_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_212",
      "param_target": "outputs",
      "param_name": "/Concat_212_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_214",
      "param_target": "outputs",
      "param_name": "/Concat_214_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_219",
      "param_target": "outputs",
      "param_name": "/Concat_219_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_221",
      "param_target": "outputs",
      "param_name": "/Concat_221_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_223",
      "param_target": "outputs",
      "param_name": "/Concat_223_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "/Concat_225",
      "param_target": "outputs",
      "param_name": "/Concat_225_output_0",
      "post_process_transpose_perm": [0,3,1,2]
    }
  ]
}
```

**Comment by PINTO0309** [comment]
I made a major modification to the `GridSample` and it works. Thanks. @Hyunseok-Kim0 
https://github.com/PINTO0309/onnx2tf/releases/tag/1.8.8
