### ISSUE TITLE
TypeError: can only concatenate list (not "NoneType") to list

### ISSUE THREAD

**Issue by nerraj-droid** [PINTO0309/onnx2tf#268]
### Issue Type

Others

### onnx2tf version number

1.8.1

### onnx version number

1.13.1

### tensorflow version number

2.12.0

### Download URL for ONNX

N/A

### Parameter Replacement JSON

```json
N/A
```

### Description

I am planning to use tflite that will be converted from this to my mobile app. However, I am encountering an issue:
When i run 'onnx2tf -i model.onnx ' the error output is this:

ERROR: The trace log is below.
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\pythonProject\lib\site-packages\onnx2tf\utils\common_functions.py", line 280, in print_wrapper_func
    result = func(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\pythonProject\lib\site-packages\onnx2tf\utils\common_functions.py", line 358, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\pythonProject\lib\site-packages\onnx2tf\utils\common_functions.py", line 49, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\pythonProject\lib\site-packages\onnx2tf\ops\Sub.py", line 158, in make_node
    input_tensor_1, input_tensor_2 = explicit_broadcast(
  File "C:\Users\Administrator\.virtualenvs\pythonProject\lib\site-packages\onnx2tf\utils\common_functions.py", line 866, in explicit_broadcast
    graph_node_input_shape2 = [1] + graph_node_input_shape2
TypeError: can only concatenate list (not "NoneType") to list
ERROR: input_onnx_file_path: model.onnx
ERROR: onnx_op_name: /vit/encoder/layer.0/layernorm_before/Sub
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

**Comment by PINTO0309** [comment]
Please share the onnx file. Or run onnxsim.
