### ISSUE TITLE
[FastestDet] ValueError: Exception encountered when calling layer "tf.nn.convolution_4" (type TFOpLambda)

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#27]
### Issue Type

Others

### onnx2tf version number

1.1.36

### Download URL for ONNX

- https://github.com/dog-qiuqiu/FastestDet
- [FastestDet.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/10096637/FastestDet.onnx.zip)

### Parameter Replacement JSON

- replace.json
```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "Gather_18",
      "param_target": "outputs",
      "param_name": "onnx::Concat_445",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_20",
      "param_target": "outputs",
      "param_name": "input.52",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_33",
      "param_target": "outputs",
      "param_name": "onnx::Concat_463",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_35",
      "param_target": "outputs",
      "param_name": "input.80",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_48",
      "param_target": "outputs",
      "param_name": "onnx::Concat_481",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_50",
      "param_target": "outputs",
      "param_name": "input.108",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_72",
      "param_target": "outputs",
      "param_name": "onnx::Concat_513",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_74",
      "param_target": "outputs",
      "param_name": "input.180",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_87",
      "param_target": "outputs",
      "param_name": "onnx::Concat_531",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_89",
      "param_target": "outputs",
      "param_name": "input.208",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_102",
      "param_target": "outputs",
      "param_name": "onnx::Concat_549",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_104",
      "param_target": "outputs",
      "param_name": "input.236",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_117",
      "param_target": "outputs",
      "param_name": "onnx::Concat_567",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_119",
      "param_target": "outputs",
      "param_name": "input.264",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_132",
      "param_target": "outputs",
      "param_name": "onnx::Concat_585",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_134",
      "param_target": "outputs",
      "param_name": "input.292",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_147",
      "param_target": "outputs",
      "param_name": "onnx::Concat_603",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_149",
      "param_target": "outputs",
      "param_name": "input.320",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_162",
      "param_target": "outputs",
      "param_name": "onnx::Concat_621",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_164",
      "param_target": "outputs",
      "param_name": "input.348",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_186",
      "param_target": "outputs",
      "param_name": "onnx::Concat_653",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_188",
      "param_target": "outputs",
      "param_name": "input.420",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_201",
      "param_target": "outputs",
      "param_name": "onnx::Concat_671",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_203",
      "param_target": "outputs",
      "param_name": "input.448",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_216",
      "param_target": "outputs",
      "param_name": "onnx::Concat_689",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Gather_218",
      "param_target": "outputs",
      "param_name": "input.476",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Transpose_261",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    },
    {
      "op_name": "Transpose_263",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    }
  ]
}
```

### Description

1. Research
2. Conversion error occured.
```
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/b920405/git/onnx2tf/onnx2tf/utils/common_functions.py", line 262, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/b920405/git/onnx2tf/onnx2tf/utils/common_functions.py", line 324, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/b920405/git/onnx2tf/onnx2tf/ops/Conv.py", line 153, in make_node
    tf.nn.convolution(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.nn.convolution_4" (type TFOpLambda).

Depth of input (44) is not a multiple of input depth of filter (24) for '{{node tf.nn.convolution_4/convolution}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Placeholder, tf.nn.convolution_4/convolution_internal/filters)' with input shapes: [1,24,44,44], [1,1,24,24].
```
3. Parameter Replacement JSON
4. Research

**Comment by PINTO0309** [comment]
```
onnx2tf -i FastestDet.onnx -prf replace.json
```
[model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/10096645/model_float32.tflite.zip)

**Comment by PINTO0309** [comment]
After v1.2.0 
```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "Transpose_261",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    },
    {
      "op_name": "Transpose_263",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    }
  ]
}
```
```
onnx2tf -i FastestDet.onnx -prf replace.json
```
