### ISSUE TITLE
[MMVC]Error occurs stating 'Resize operations other than 4D and 5D are not supported' for a 3D operation

### ISSUE THREAD

**Issue by stealthinu** [PINTO0309/onnx2tf#283]
### Issue Type

Others

### onnx2tf version number

1.8.10

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc1

### Download URL for ONNX

[make_sin_d.zip](https://github.com/PINTO0309/onnx2tf/files/11137146/make_sin_d.zip)

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose
Product development

2. What
I encountered an issue when trying to convert an ONNX file using onnx2tf. The error message I received is as follows:

```
$ onnx2tf -i make_sin_d.onnx -kat f0
```
```
INFO: onnx_op_type: Resize onnx_op_name: /Resize_1
INFO:  input_name.1: /Where_3_output_0 shape: [1, 1, 42] dtype: float32
INFO:  input_name.2:  shape: None dtype: None
INFO:  input_name.3:  shape: None dtype: None
INFO:  input_name.4: /Concat_8_output_0 shape: [3] dtype: <class 'numpy.int64'>
INFO:  output_name.1: /Resize_1_output_0 shape: [1, 1, 5376] dtype: float32
ERROR: Currently, Resize operations other than 4D and 5D are not supported. Pull requests are welcome.
graph_node.name: /Resize_1 shape: (1, 1, 42)
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/stealth/anaconda3/envs/mmvc15/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 280, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/stealth/anaconda3/envs/mmvc15/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 358, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/stealth/anaconda3/envs/mmvc15/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 49, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/stealth/anaconda3/envs/mmvc15/lib/python3.9/site-packages/onnx2tf/ops/Resize.py", line 243, in make_node
    sys.exit(1)
SystemExit: 1
ERROR: input_onnx_file_path: make_sin_d.onnx
ERROR: onnx_op_name: /Resize_1
```

3. How
I tried adding input parameter options to the test.

```
$ onnx2tf -i make_sin_d.onnx -ois f0:1,1,42 -cotof -cotoa 1e-1 -kat f0
```

I checked the vector size using Netron.

![image](https://user-images.githubusercontent.com/345236/229482271-057b2aa6-b8f7-4e96-86f7-c96547088170.png)

4. Why
I would like to make these modifications because I want to run the model in TFLite.

5. Resources
None

**Comment by PINTO0309** [comment]
I understand what you are saying, but unfortunately it is impossible.

https://www.tensorflow.org/api_docs/python/tf/image/resize

![image](https://user-images.githubusercontent.com/33194443/229483075-32f82df0-46a5-42a9-b1ff-5572dbc3d18b.png)

Pseudo-scaling should be reimplemented using `TransposeConv` or similar.

**Comment by PINTO0309** [comment]
https://github.com/ultralytics/yolov5/issues/7520

**Comment by PINTO0309** [comment]
It looks `asymmetric`, does this specification satisfy what you want to do?

https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling1D

![image](https://user-images.githubusercontent.com/33194443/229490165-18492043-f0fb-46b5-9535-dad8737bdd3e.png)

**Comment by stealthinu** [comment]
I appreciate your consistently suggestions. Thank you very much!

This process is much simpler. It generates a guiding waveform based on the frequency (f0). In this case, we are not using Conv1d or ConvTranspose1d.

In this case, the input parameter vector is set as (1, 1, 42), but in reality, during inference, only (42) is needed. Likewise, the output should be (336) instead of (1, 1, 336). If we use this format, wouldn't it avoid the resize issue?

**Comment by stealthinu** [comment]
The size of the input and output vectors for this model is as follows.

inputs
name:f0 shape:[1, 1, 42]        dtype:tensor(float)

outputs
name:in_batch   shape:[1, 1, 5376]      dtype:tensor(float)
name:dfs_batch  shape:[1, 1, 336]       dtype:tensor(float)
name:118        shape:[1, 1, 1344]      dtype:tensor(float)
name:264        shape:[1, 1, 2688]      dtype:tensor(float)
name:538        shape:[1, 1, 5376]      dtype:tensor(float)

**Comment by PINTO0309** [comment]
I don't understand why the `Tile` OP is not good enough.

**Comment by stealthinu** [comment]
The following code is the problematic section that I'm encountering:

```python
    def __init__(
        self,
        sample_rate=24000,
        hop_size=120,
        sine_amp=0.1,
        noise_amp=0.003,
    ):

    def sinusoid(self, f0):
        """Calculate sine signals.

        Args:
            f0 (Tensor): F0 tensor (B, 1, T // hop_size).

        Returns:
            Tensor: Sines generated following NSF (B, 1, T).

        """
        B, _, T = f0.size()
        vuv = interpolate((f0 > 0) * torch.ones_like(f0), T * self.hop_size)
        radious = (interpolate(f0, T * self.hop_size) / self.sample_rate) % 1
        sine = vuv * torch.sin(torch.cumsum(radious, dim=2) * 2 * np.pi) * self.sine_amp
        if self.noise_amp > 0:
            noise_amp = vuv * self.noise_amp + (1.0 - vuv) * self.noise_amp / 3.0
            noise = torch.randn((B, 1, T * self.hop_size), device=f0.device) * noise_amp
            sine = sine + noise

        return sine
```

**Comment by stealthinu** [comment]
I might have finally understood what PINTO mentioned in the initial comment. In order to use TensorFlow's resize function, the input must be in the format (B, H, W, C). So, is the issue that the conversion does not work well since the target we want to convert here is (B, 1, W)? If that's the case, would it be possible to convert it if we change it to (B, 1, W, 1) before passing it to the function?

**Comment by PINTO0309** [comment]
>So, is the issue that the conversion does not work well since the target we want to convert here is (B, 1, W)?

That is correct. Thus, in my second comment, I suggested an `Upsampling` operation that might replace `Resize`. In any case, since we have known for quite some time that there is no fully compatible OP between ONNX and TensorFlow, I thought I would implement it if the behavior of `Upsampling1D` is what you expect.

https://github.com/PINTO0309/onnx2tf/issues/283#issuecomment-1494107594

![image](https://user-images.githubusercontent.com/33194443/229560599-5fe9b13e-5ff8-4408-8f14-b7f73b842277.png)

`UpSampling1D` is similar to NCW in ONNX.

> If that's the case, would it be possible to convert it if we change it to (B, 1, W, 1) before passing it to the function?

Yes, we can. However, I feel it is not a good idea to make non-essential changes to the model. It is my own way of thinking that it is better to match the standard behavior of the framework as much as possible with the model design philosophy you expect. This is just my meddling.

However, if there is a demand for 1D Upsampling, I would like to do as much conversion as possible on the tool side without the model designer having to do any complicated tricks.

**Comment by stealthinu** [comment]
I looked into it a bit more closely.

It seems that ONNX's "Resize" is designed with image resizing in mind, so it also includes interpolation. In other words, it appears that the "Resize" operation alone encompasses the functionality of "torch.nn.functional.interpolate."

https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize
if coordinate_transformation_mode is "asymmetric",
```
x_original = x_resized / scale
```

Therefore, I thought it wouldn't be possible to replace it with "Upsampling1D."

**Comment by PINTO0309** [comment]
Thank you for fully understanding my intent. 

According to the discussion, since there are differences between ONNX (or PyTorch) and TensorFlow that are not complementary in terms of specifications, we believe that the following two things can be done with this onnx2tf.

1. Dare to implement an alternative conversion logic with `Upsampling1D` with the understanding that there is a difference in specification.
2. Forced implementation with a combination of very redundant OPs in TensorFlow to perfectly trace 1D Resize in ONNX.

Both have advantages and disadvantages. Thus, the reality is that at my current level of knowledge, I have not been able to come up with a good, realistic idea that expresses the functionality you wish to achieve.

**Comment by stealthinu** [comment]
Yes, thanks to PINTO's advice, I was able to gain a better understanding of the differences between ONNX and TensorFlow.
I then tried addressing the issue by modifying the torch-side model to be in the shape of (B, 1, 1, W).

```python
    def sinusoid(self, f0):
        """Calculate sine signals.

        Args:
            f0 (Tensor): F0 tensor (B, 1, T // hop_size).

        Returns:
            Tensor: Sines generated following NSF (B, 1, T).

        """
        f0 = f0.unsqueeze(-2)
        B, _, _, T= f0.size()
        vuv = interpolate((f0 > 0) * torch.ones_like(f0), scale_factor=(1, self.hop_size))
        radious = (interpolate(f0, scale_factor=(1, self.hop_size)) / self.sample_rate) % 1
        sine = vuv * torch.sin(torch.cumsum(radious, dim=3) * 2 * np.pi) * self.sine_amp
        if self.noise_amp > 0:
            noise_amp = vuv * self.noise_amp + (1.0 - vuv) * self.noise_amp / 3.0
            noise = torch.randn((B, 1, 1, T * self.hop_size), device=f0.device) * noise_amp
            sine = sine + noise
        sine = sine.squeeze(-2)

        return sine
```

With this change, I was able to confirm that the conversion using onnx2tf worked successfully.

![image](https://user-images.githubusercontent.com/345236/229737598-755acff3-0806-47a5-97fe-8fb5df487e6f.png)

**Comment by PINTO0309** [comment]
I see. So, the method of forcibly breaking the shape into 4D and resizing it seems to make sense.

**Comment by stealthinu** [comment]
Yes, I also believe that changing the tensor's shape to 4D, applying the Resize, and then reverting it back to its original shape would be effective.

**Comment by PINTO0309** [comment]
- memorandum
  1. Reshape` to force `H` to be added when 3D input comes in
  2. Resize` in 4D. However, the `H` dimension is scaled by a factor of 1.
  3.  Again, `Reshape` to 3D so that the `H` dimension is removed

**Comment by PINTO0309** [comment]
- Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.8.12
- `Resize`
  - Implement `Resize` workaround for 1D tensors
  - https://github.com/PINTO0309/onnx2tf/files/11137146/make_sin_d.zip
  - onnx
    ![image](https://user-images.githubusercontent.com/33194443/229763988-eb4d47d6-a2fa-4fd5-8be9-73fec748ad63.png)
  - tflite
    ![image](https://user-images.githubusercontent.com/33194443/229764321-43a3e527-c2e7-42c3-b07b-3f96a45eea78.png)

**Comment by PINTO0309** [comment]
I have confirmed that the conversion works fine. I will close this issue once, but if other issues arise, please post a separate issue.

**Comment by stealthinu** [comment]
Thank you so much!!
I tried converting the ONNX generated without modifying the torch-side model and confirmed that the conversion worked without any issues.
