### ISSUE TITLE
[PaddleOCR] Unable to convert paddleOCR model to tensorflow/keras only tflite

### ISSUE THREAD

**Issue by herbzhao** [PINTO0309/onnx2tf#360]
### Issue Type

Others

### onnx2tf version number

1.11.10

### onnx version number

1.13.1

### onnxruntime version number

1.13.1

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.12.0

### Download URL for ONNX

https://filebin.net/d4069w92cmtghuv7/inference_ops15.onnx
https://filebin.net/d4069w92cmtghuv7/inference_ops12.onnx

### Parameter Replacement JSON

```json
N/A
```

### Description

I have converted the paddleOCR model to ONNX. 
And using the onnx2tf, i want to obtain a tflite model to ultimately be quantized model and run on my NPU.

I understand that we may want to do QAT for proper quantization, for this my colleague wants keras / tensorflow model. 
At the moment, when I run the conversion using 
`onnx2tf -i inference_ops15.onnx -ois x:1,3,48,320  -kat x ` This produces a usable tflite model (fp16/32)
But if i specify 
`-osd` or `-okv3` it will complain. Additionally any quantization tags also will not work. 

When specify the -osd
```
============================================================================================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
____________________________________________________________________________________________________________________________________________

saved_model output started ==========================================================
ERROR: Tried to export a function which references an 'untracked' resource. TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
        Function name = b'__inference_signature_wrapper_16308'
        Captured Tensor = <ResourceHandle(name="Resource-0-at-0x8091830", device="/job:localhost/replica:0/task:0/device:CPU:0", container="Anonymous", type="tensorflow::Var", dtype and shapes : "[ DType enum: 1, Shape: [3,3,1,64] ]")>
        Trackable referencing this tensor = <tf.Variable 'p2o.Conv.7/kernel:0' shape=(3, 3, 1, 64) dtype=float32>
        Internal Tensor = Tensor("16074:0", shape=(), dtype=resource)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 936, in convert
    tf.saved_model.save(model, output_folder_path)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1240, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1276, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1455, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1410, in _build_meta_graph_impl
    asset_info, exported_graph = _fill_meta_graph_def(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 803, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, object_map)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 610, in _generate_signatures
    outputs = object_map[function](**{
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 40, in __call__
    export_captures = _map_captures_to_created_tensors(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 69, in _map_captures_to_created_tensors
    _raise_untracked_capture_error(function.name, exterior, interior)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 93, in _raise_untracked_capture_error
    raise AssertionError(msg)
AssertionError: Tried to export a function which references an 'untracked' resource. TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
        Function name = b'__inference_signature_wrapper_16308'
        Captured Tensor = <ResourceHandle(name="Resource-0-at-0x8091830", device="/job:localhost/replica:0/task:0/device:CPU:0", container="Anonymous", type="tensorflow::Var", dtype and shapes : "[ DType enum: 1, Shape: [3,3,1,64] ]")>
        Trackable referencing this tensor = <tf.Variable 'p2o.Conv.7/kernel:0' shape=(3, 3, 1, 64) dtype=float32>
        Internal Tensor = Tensor("16074:0", shape=(), dtype=resource)
Float32 tflite output complete!
Float16 tflite output complete!
```

When specify quantizaiton with tflite
```

saved_model output started ==========================================================
ERROR: Tried to export a function which references an 'untracked' resource. TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
        Function name = b'__inference_signature_wrapper_16308'
        Captured Tensor = <ResourceHandle(name="Resource-0-at-0x2c81120", device="/job:localhost/replica:0/task:0/device:CPU:0", container="Anonymous", type="tensorflow::Var", dtype and shapes : "[ DType enum: 1, Shape: [3,3,1,64] ]")>
        Trackable referencing this tensor = <tf.Variable 'p2o.Conv.7/kernel:0' shape=(3, 3, 1, 64) dtype=float32>
        Internal Tensor = Tensor("16074:0", shape=(), dtype=resource)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 936, in convert
    tf.saved_model.save(model, output_folder_path)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1240, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1276, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1455, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1410, in _build_meta_graph_impl
    asset_info, exported_graph = _fill_meta_graph_def(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 803, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, object_map)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 610, in _generate_signatures
    outputs = object_map[function](**{
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 40, in __call__
    export_captures = _map_captures_to_created_tensors(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 69, in _map_captures_to_created_tensors
    _raise_untracked_capture_error(function.name, exterior, interior)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 93, in _raise_untracked_capture_error
    raise AssertionError(msg)
AssertionError: Tried to export a function which references an 'untracked' resource. TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
        Function name = b'__inference_signature_wrapper_16308'
        Captured Tensor = <ResourceHandle(name="Resource-0-at-0x2c81120", device="/job:localhost/replica:0/task:0/device:CPU:0", container="Anonymous", type="tensorflow::Var", dtype and shapes : "[ DType enum: 1, Shape: [3,3,1,64] ]")>
        Trackable referencing this tensor = <tf.Variable 'p2o.Conv.7/kernel:0' shape=(3, 3, 1, 64) dtype=float32>
        Internal Tensor = Tensor("16074:0", shape=(), dtype=resource)
Float32 tflite output complete!
Float16 tflite output complete!
Traceback (most recent call last):
  File "/usr/local/bin/onnx2tf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 2073, in main
    model = convert(
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/onnx2tf.py", line 1072, in convert
    loaded_saved_model = tf.saved_model.load(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/load.py", line 836, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/load.py", line 941, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 58, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 116, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: onnx2tf/en_PP-OCRv3_rec_infer_onnx/inference_ops15/{saved_model.pbtxt|saved_model.pb}
```

**Comment by PINTO0309** [comment]
To begin with, the ONNX conversion from PaddlePaddle seems to have failed before converting with onnx2tf. Even Netron cannot display the model properly.

- inference_ops12.onnx
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/0970553b-4089-4b8a-93a4-81e0c92470be)

**Comment by PINTO0309** [comment]
```
onnx2tf -i inference_ops15.onnx -osd -dgc
```
```
saved_model output started ==========================================================
saved_model output complete!
Float32 tflite output complete!
Float16 tflite output complete!
```

**Comment by PINTO0309** [comment]
The inability of `GroupConvolution` to output in saved_model or keras_v3 format is an obvious TensorFlow spec bug. You can then use the `-oiqt` option to quantize directly to INT8 without using the `-osd` option.
