### ISSUE TITLE
PRelu "not compatible with provided weight shape" conversion problem

### ISSUE THREAD

**Issue by Jukyy** [PINTO0309/onnx2tf#418]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

1.14.4

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

https://ufile.io/i4ioexwx
[example.zip](https://github.com/PINTO0309/onnx2tf/files/12066487/example.zip)

### Parameter Replacement JSON

```json
{}
```

### Description

1. Description

Trying to convert model with PRelu layer where input tensor has the same dimensions for channel height and width (in this case `INFO:  input_name.1: 9 shape: [1, 4, 4, 4] dtype: float32`)

<details>

<summary>2. Console output</summary>

```
user@953ad4664a83:/workdir$ onnx2tf -i example.onnx

Model optimizing started ============================================================
Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃                    ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ BatchNormalization │ 1              │ 0                │
│ Constant           │ 7              │ 4                │
│ Conv               │ 1              │ 1                │
│ Flatten            │ 1              │ 1                │
│ MatMul             │ 1              │ 1                │
│ PRelu              │ 1              │ 1                │
│ Model Size         │ 3.5KiB         │ 3.4KiB           │
└────────────────────┴────────────────┴──────────────────┘

Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃            ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Constant   │ 4              │ 4                │
│ Conv       │ 1              │ 1                │
│ Flatten    │ 1              │ 1                │
│ MatMul     │ 1              │ 1                │
│ PRelu      │ 1              │ 1                │
│ Model Size │ 3.4KiB         │ 3.4KiB           │
└────────────┴────────────────┴──────────────────┘

Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃            ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Constant   │ 4              │ 4                │
│ Conv       │ 1              │ 1                │
│ Flatten    │ 1              │ 1                │
│ MatMul     │ 1              │ 1                │
│ PRelu      │ 1              │ 1                │
│ Model Size │ 3.4KiB         │ 3.4KiB           │
└────────────┴────────────────┴──────────────────┘

Model optimizing complete!

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model convertion started ============================================================
INFO: input_op_name: input_0 shape: [1, 3, 8, 8] dtype: float32

INFO: onnx_op_type: Conv onnx_op_name: Conv_0
INFO:  input_name.1: input_0 shape: [1, 3, 8, 8] dtype: float32
INFO:  input_name.2: 33 shape: [4, 3, 3, 3] dtype: float32
INFO:  input_name.3: 38 shape: [4] dtype: float32
INFO:  output_name.1: 9 shape: [1, 4, 4, 4] dtype: float32
INFO: tf_op_type: convolution_v2
INFO:  input.1.input: name: tf.compat.v1.pad/Pad:0 shape: (1, 10, 10, 3) dtype: <dtype: 'float32'>
INFO:  input.2.weights: shape: (3, 3, 3, 4) dtype: <dtype: 'float32'>
INFO:  input.3.bias: shape: (4,) dtype: <dtype: 'float32'>
INFO:  input.4.strides: val: [2, 2]
INFO:  input.5.dilations: val: [1, 1]
INFO:  input.6.padding: val: VALID
INFO:  input.7.group: val: 1
INFO:  output.1.output: name: tf.math.add/Add:0 shape: (1, 4, 4, 4) dtype: <dtype: 'float32'>

INFO: onnx_op_type: PRelu onnx_op_name: PRelu_2
INFO:  input_name.1: 9 shape: [1, 4, 4, 4] dtype: float32
INFO:  input_name.2: 16 shape: [4, 1, 1] dtype: float32
INFO:  output_name.1: 12 shape: [1, 4, 4, 4] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/utils/common_functions.py", line 283, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx2tf/ops/PRelu.py", line 116, in make_node
    PReLU(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1038, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 2668, in _maybe_build
    self.set_weights(self._initial_weights)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1799, in set_weights
    raise ValueError(
ValueError: Layer weight shape (1, 1, 4) not compatible with provided weight shape (4, 1, 1)
ERROR: input_onnx_file_path: example.onnx
ERROR: onnx_op_name: PRelu_2
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```
</details>

3. Solving the problem

The problem was solved by adding a condition which checks for the last dimension of slope tensor. If the last dimension isn't 1, then it should be transposed.

```diff
diff --git a/onnx2tf/ops/PRelu.py b/onnx2tf/ops/PRelu.py
index b1e452b..70765b6 100644
--- a/onnx2tf/ops/PRelu.py
+++ b/onnx2tf/ops/PRelu.py
@@ -72,6 +72,11 @@ def make_node(
         tf_layers_dict= tf_layers_dict
     )

+    if slope.shape[-1] == 1:
+        transpose_perm = [0] + [i+2 for i in range(len(input_tensor.shape)-2)] + [1]
+        if isinstance(slope, np.ndarray):
+            slope: np.ndarray = slope.transpose(transpose_perm)
+
     graph_node_output: gs.Variable = graph_node.outputs[0]
     shape = graph_node_output.shape
     dtype = graph_node_output.dtype
```
Is this a correct way to solve this problem in general or am I missing some edge-case where this condition will break?

4. Why?

Solving this issue will enable full automation of converting models which contain PRelu layer.

**Comment by PINTO0309** [comment]
Thanks for pointing that out so well.

`PRelu` is trickier to work with than any other activation function, and there are considerably more considerations and complications regarding the relationship between `input` and `slope`. Therefore, as you suggested, just determining if the trailing shape is `1` may cause the conversion to fail in other models.

I have just fixed the problem and am running a test with CI, so the problem should be resolved in a release in a few hours.

**Comment by Jukyy** [comment]
Thanks for the very quick response.
