### ISSUE TITLE
[TODO] Fix Abort problem with `Inverse` transformations when the input tensor is `np.ndarray`.

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#421]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.14.5

### onnx version number

1.13.1

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

1.13.0

### Download URL for ONNX

[19_warpAffine_256x192_16.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/12135939/19_warpAffine_256x192_16.onnx.zip)

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Personal
2. Fix Abort problem with `Inverse` transformations when the input tensor is `np.ndarray`.

```
Model convertion started ============================================================
INFO: input_op_name: affine_src shape: [1, 3, 2] dtype: float32
INFO: input_op_name: affine_dst shape: [1, 3, 2] dtype: float32
INFO: input_op_name: aff_homo_img shape: [1, 3, 256, 192] dtype: float32

INFO: onnx_op_type: Concat onnx_op_name: 00_Concat
INFO:  input_name.1: affine_src shape: [1, 3, 2] dtype: float32
INFO:  input_name.2: 00_Constant_output_0 shape: [1, 3, 1] dtype: float32
INFO:  output_name.1: output_affine_A shape: [1, 3, 3] dtype: float32
INFO: tf_op_type: concat
INFO:  input.1.input0: name: affine_src shape: (1, 3, 2) dtype: <dtype: 'float32'> 
INFO:  input.2.input1: shape: (1, 3, 1) dtype: <dtype: 'float32'> 
INFO:  input.3.axis: val: 2 
INFO:  output.1.output: name: tf.concat/concat:0 shape: (1, 3, 3) dtype: <dtype: 'float32'> 

INFO: onnx_op_type: Inverse onnx_op_name: 06_Inverse_0
INFO:  input_name.1: output_src_norm_trans_src_pix shape: [1, 3, 3] dtype: float32
INFO:  output_name.1: 05_inverse_output shape: [1, 3, 3] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/b920405/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 283, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/b920405/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/b920405/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/b920405/.local/lib/python3.10/site-packages/onnx2tf/ops/Inverse.py", line 77, in make_node
    if 'nhwc' in tf_layers_dict[graph_node_input.name].keys() else False
AttributeError: 'numpy.ndarray' object has no attribute 'name'
ERROR: input_onnx_file_path: 19_warpAffine_256x192_16.onnx
ERROR: onnx_op_name: 06_Inverse_0
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.14.6
