### ISSUE TITLE
[Conv-TasNet] Facing issue in converting Conv-TasNet model 

### ISSUE THREAD

**Issue by ajithvallabai** [PINTO0309/onnx2tf#447]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.15.7

### onnx version number

1.14.0

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

https://drive.google.com/file/d/189UHTs9OvDiNBc6BiZDG5zde2zSyTe6E/view?usp=sharing

### Parameter Replacement JSON

```json
{
    "format_version": 1,
    "operations": [
      {
        "op_name": "/decoder/Reshape",
        "param_target": "inputs",
        "param_name": "concat",
        "post_process_transpose_perm": [0,1,2,3,4]
      }
    ]
  }
```

### Description

1. Personal development
2. 
<img width="578" alt="scatter_ele" src="https://github.com/PINTO0309/onnx2tf/assets/8075112/92c589fc-6e20-4baf-a8a7-6ac788bdb516">

Error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_4_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Ranks of all input tensors should match: shape[0] = [256,2,2,10,1] vs. shape[2] = [2,1,256,2,2,10,1] [Op:ConcatV2] name: concat

ERROR: input_onnx_file_path: conv_tasnet.onnx
ERROR: onnx_op_name: /decoder/ScatterElements
```
3. I tried to use parameter replacement.json but its of no luck i am not sure how to use it to resolve this problem.
Command that i tried 
```
onnx2tf -i conv_tasnet.onnx -kat mixtures -cotof -cotoa 1e-4 -prf replace_conv_tasnet.json 
```
5. I am working on audio separation process for which i need tflite models
6. Repo link : https://github.com/kaituoxu/Conv-TasNet

Onnx conversion script:

```
import onnx
import torch

from conv_tasnet import ConvTasNet


def convertoOnnx():
    device = torch.device('cpu')
    # Create model.
    model = ConvTasNet(256, 20, 256, 512, 3, 8, 4,
                       2, norm_type="gLN", causal=0,
                       mask_nonlinear="relu")

    model.to(device)
    dummy_input =  {'mixtures': torch.ones(256, 20).to(torch.device('cpu'))}

    onnx_model_path = 'conv_tasnet.onnx'
    torch.onnx.export(model, dummy_input["mixtures"], onnx_model_path, verbose=True, opset_version=12)
def main():
    convertoOnnx()

if __name__ == "__main__":

    main()
```

**Comment by PINTO0309** [comment]
It must be a bug in PyTorch. To begin with, you cannot reason with the standard onnxruntime. Have you checked?

```bash
sit4onnx -if conv_tasnet.onnx -oep cpu

INFO: file: conv_tasnet.onnx
INFO: providers: ['CPUExecutionProvider']
INFO: input_name.1: onnx::Unsqueeze_0 shape: [256, 20] dtype: float32
Traceback (most recent call last):
  File "/home/b920405/.local/bin/sit4onnx", line 8, in <module>
    sys.exit(main())
  File "/home/b920405/.local/lib/python3.10/site-packages/sit4onnx/onnx_inference_test.py", line 506, in main
    final_results = inference(
  File "/home/b920405/.local/lib/python3.10/site-packages/sit4onnx/onnx_inference_test.py", line 357, in inference
    results = onnx_session.run(
  File "/home/b920405/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running ScatterElements node. Name:'/decoder/ScatterElements' Status Message: Indices and updates must have the same rank
```

Embedded `indicies` that ignore the specifications in the ONNX OP specification. There is no obligation to convert ONNX files that ignore the specifications.

- `ScatterElements`
  https://github.com/onnx/onnx/blob/main/docs/Changelog.md#scatterelements-11
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/ec05bffb-8249-4c24-a125-76de44a3cc82)

  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/953483e5-b833-4bb3-9792-4501c647dd49)

**Comment by ajithvallabai** [comment]
thanks for the info

**Comment by ajithvallabai** [comment]
subject : Facing Nan values in tflite output
@PINTO0309 i some how managed to remove _scaterelements_ node from the model so now i am able to run properly in onnx standard runtime and below is the code which i used to verify it and its successful in verification.

```
import onnx
import torch
import torch.nn as nn
import torch.nn.init as init
from conv_tasnet import ConvTasNet
import onnxruntime
import numpy as np


def convertoOnnx():

    device = torch.device('cpu')

    
    # Create the super-resolution model by using the above model definition.
    model = ConvTasNet(256, 20, 256, 512, 3, 8, 4,
                       2, norm_type="gLN", causal=0,
                       mask_nonlinear="softmax")
    model.eval()
    model.to(device)
    dummy_input = torch.ones(256, 20).to(torch.device('cpu'))

    # Export the model
    torch.onnx.export(model,               # model being run
                    dummy_input,                         # model input (or a tuple for multiple inputs)
                    "conv_tasnet_39nx_7.onnx",   # where to save the model (can be a file or file-like object)
                    export_params=True,        # store the trained parameter weights inside the model file
                    opset_version=12,          # the ONNX version to export the model to
                    do_constant_folding=True,  # whether to execute constant folding for optimization
                    input_names = ['input'],   # the model's input names
                    output_names = ['output'], # the model's output names
                    #dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                    #                'output' : {0 : 'batch_size'}}
                                    )
    #from conv_tasnet import ConvTasNet
    ort_session = onnxruntime.InferenceSession("conv_tasnet_39nx_7.onnx")

    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    x = torch.randn(256, 20).to(torch.device('cpu'))

    device = torch.device('cpu')

    torch_out = model(x)

    # compute ONNX Runtime output prediction
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
    ort_outs = ort_session.run(None, ort_inputs)

    # compare ONNX Runtime and PyTorch results
    np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05)
    print("torch out")
    print(to_numpy(torch_out))
    print("onnx out")
    print(ort_outs[0])
    print("Exported model has been tested with ONNXRuntime, and the result looks good!")

def main():

    convertoOnnx()

if __name__ == "__main__":

    main()
```

I use below onnx model for conversion with onnx2tf  and it also has the tflite model after conversion
https://drive.google.com/file/d/1vzo9P5lEaLLNBra4mKVhYe_5mCREEE6J/view?usp=sharing


this is the command i used to convert and there were no errors during the conversion  ```onnx2tf -i conv_tasnet_39nx_7.onnx -kat mixtures  -cotof -cotoa 1e-4``` but when i do inference with tflite model i am getting "nan" values in the matrix of 250,2,20

```

import tensorflow as tf
import time


# Load TFLite model
interpreter = tf.lite.Interpreter(model_path="./saved_model/conv_tasnet_39nx_7_float32.tflite")
interpreter.allocate_tensors()
tensor_shape = (256, 20)
input_data = {'waveform': tf.ones(tensor_shape, dtype=tf.float32) }

# Load and preprocess
input_details = interpreter.get_input_details()
input_shape = input_details[0]['shape']
print(input_shape)

# Run inference
interpreter.set_tensor(input_details[0]['index'], input_data["waveform"])
separate_time = time.time()
interpreter.invoke()
print("Done! {:.3f} s".format(time.time() - separate_time))
output_details = interpreter.get_output_details()
output_data = interpreter.get_tensor(output_details[0]['index'])

# Check the device used for inference
# output_tensor = interpreter.tensor(output_data)
# print("Inference was performed on:", output_details.device_name)
output_data = []
for output_detail in output_details:
    output_data.append(interpreter.get_tensor(output_detail['index']))

print(output_data)
 
```

**Comment by PINTO0309** [comment]
```
onnx2tf -i conv_tasnet_39nx_7.onnx \
-cotof \
-onimc "/separator/network/network.2/network.2.0/network.2.0.0/net/net.1/PRelu_output_0"
```
```
[array([[[-0.00417661,  0.13557428,  0.00747245, ..., -0.        ,
          0.08287186,         nan]],

       [[-0.01359006,  0.14600608,  0.03704544, ..., -0.        ,
          0.13754255,         nan]],

       [[-0.01396633,         nan, -0.        , ..., -0.        ,
         -0.        ,         nan]],

       ...,

       [[-0.02858675,  0.03051723, -0.        , ...,  0.00328746,
          0.00181477,         nan]],

       [[-0.00639979,  0.17624335,  0.02880344, ..., -0.        ,
          0.02940094,         nan]],

       [[-0.0115342 ,  0.07608917,  0.0747497 , ..., -0.        ,
          0.08765636,         nan]]], dtype=float32)]
```

**Comment by PINTO0309** [comment]
I decided to add to the README the numerous workarounds I have implemented in this tool, as they do not seem to be understood by most engineers.

**Comment by ajithvallabai** [comment]
thanks
