### ISSUE TITLE
[TODO] Implementation of `Proto Splitter` (breakthrough of 2GB contract for Protocol Buffers)

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#455]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.15.12

### onnx version number

1.13.1

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

1.13.0

### Download URL for ONNX

N/A

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Personal
2. Implementation of `Proto Splitter` (breakthrough of 2GB contract for Protocol Buffers)
  https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/proto_splitter

Implementing this in the backend should make it possible to break through the 2GB limit of Protocol Buffers.

**Comment by PINTO0309** [comment]
- TensorFlow v2.15.0
  ```
  ERROR: The option `experimental_image_format` is disabled in OSS.
  Traceback (most recent call last):
    File "/home/b920405/git/onnx2tf/onnx2tf/onnx2tf.py", line 1173, in convert
      tf.saved_model.save(model, output_folder_path, options=tf.saved_model.SaveOptions(experimental_image_format=True))
    File "/home/b920405/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/save_options.py", line 189, in __init__
      raise ValueError(
  ValueError: The option `experimental_image_format` is disabled in OSS.
  ```

**Comment by PINTO0309** [comment]
- test code
  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/proto_splitter_save_test.py
