### ISSUE TITLE
[DNN-based_source_separation] Facing issue in Mul node during conversion

### ISSUE THREAD

**Issue by ajithvallabai** [PINTO0309/onnx2tf#460]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.15.7

### onnx version number

1.14.0

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

https://drive.google.com/file/d/1R8k2T52oggZ7qkSrlNv5o-p-IyPzuVHJ/view?usp=sharing

### Parameter Replacement JSON

```json
{
    "format_version": 1,
    "operations": [
      {
        "op_name": "/separator/Reshape",
        "param_target": "outputs",
        "param_name": "onnx::Mul_724",
        "post_process_transpose_perm": [0,3,2,1]
      }
    ]
  }
```

### Description

1. Personal dev
2. Error log
```
INFO: onnx_op_type: InstanceNormalization onnx_op_name: /separator/tdcn/net.1/net.2/separable_conv1d/norm1d/norm/InstanceNormalization
INFO:  input_name.1: /separator/tdcn/net.1/net.2/separable_conv1d/norm1d/norm/Reshape_output_0 shape: [2, 1, 12288] dtype: float32
INFO:  input_name.2: /separator/norm1d/norm/Constant_1_output_0 shape: (1,) dtype: float32
INFO:  input_name.3: /separator/norm1d/norm/Constant_2_output_0 shape: (1,) dtype: float32
INFO:  output_name.1: /separator/tdcn/net.1/net.2/separable_conv1d/norm1d/norm/InstanceNormalization_output_0 shape: [2, 1, 12288] dtype: float32
^CERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 282, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 355, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/ops/InstanceNormalization.py", line 124, in make_node
    val_model = tf.keras.Model(
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/tensorflow/python/trackable/base.py", line 204, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/keras/src/engine/functional.py", line 167, in __init__
    self._init_graph_network(inputs, outputs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/tensorflow/python/trackable/base.py", line 204, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/keras/src/engine/functional.py", line 274, in _init_graph_network
    self._layer_call_argspecs[layer] = tf_inspect.getfullargspec(
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/keras/src/utils/tf_inspect.py", line 286, in getfullargspec
    return _getfullargspec(target)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/inspect.py", line 1195, in getfullargspec
    if param.default is not param.empty:
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/inspect.py", line 2552, in default
    @property
KeyboardInterrupt
```
3. I visualized in netron app saw that while unsqueeze and reshape are being multipled issue occurs due to dimension mismatch. So i wrote a parameter.json for permutation but it seems that its not working . May be "param_name": "onnx::Mul_724" is wrong i think not sure of it.
 Command used : ```onnx2tf -i conv_tasnet_dnn.onnx -prf replace_parameter.json -cotof -cotoa 1e-4 ```
5. I am able to train the repo, tested with onnxruntime output matches with torch but not able to convert onnx to tflite
6. out.txt

[out_dnn_convtasnet.txt](https://github.com/PINTO0309/onnx2tf/files/12397398/out_dnn_convtasnet.txt)

Repo: https://github.com/tky823/DNN-based_source_separation

below is onnx conversion script
```
import sys 
sys.path.append("../src")
from models.conv_tasnet import ConvTasNet

import onnx
import torch
import torch.nn as nn
import torch.nn.init as init
# from conv_tasnet import ConvTasNet
import onnxruntime
import numpy as np


def convertoOnnx():

    device = torch.device('cpu')

    
    # Create the super-resolution model by using the above model definition.
    # model = ConvTasNet(256, 20, 256, 512, 3, 8, 4,
    #                    2, norm_type="gLN", causal=0,
    #                    mask_nonlinear="softmax")
 
    model = ConvTasNet(
        256, 20, stride=20//2, in_channels=2, enc_basis='trainable', dec_basis='trainable', enc_nonlinear=None,
        window_fn='', enc_onesided=0, enc_return_complex=0,
        sep_hidden_channels=512, sep_bottleneck_channels=256, sep_skip_channels=128, sep_kernel_size=3, sep_num_blocks=4, sep_num_layers=10,
        dilated=1, separable=1, sep_nonlinear='prelu', sep_norm=1, mask_nonlinear='sigmoid',
        causal=0,
        n_sources=4
    )
    model.eval()
    model.to(device)
    dummy_input = torch.ones(2, 1, 2, 250).to(torch.device('cpu'))
    model(dummy_input)

    # Export the model
    torch.onnx.export(model,               # model being run
                    dummy_input,                         # model input (or a tuple for multiple inputs)
                    "conv_tasnet_dnn.onnx",   # where to save the model (can be a file or file-like object)
                    export_params=True,        # store the trained parameter weights inside the model file
                    opset_version=12,          # the ONNX version to export the model to
                    do_constant_folding=True,  # whether to execute constant folding for optimization
                    input_names = ['input'],   # the model's input names
                    output_names = ['output'], # the model's output names
                    #dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                    #                'output' : {0 : 'batch_size'}}
                                   )
    #from conv_tasnet import ConvTasNet
    ort_session = onnxruntime.InferenceSession("conv_tasnet_dnn.onnx")

    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    x = torch.randn(2, 1, 2, 250).to(torch.device('cpu'))

    device = torch.device('cpu')

    torch_out = model(x)

    # compute ONNX Runtime output prediction
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
    ort_outs = ort_session.run(None, ort_inputs)

    # compare ONNX Runtime and PyTorch results
    np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05) #atol=1e-05
    print("torch out")
    print(to_numpy(torch_out))
    print("onnx out")
    print(ort_outs[0])
    print("Exported model has been tested with ONNXRuntime, and the result looks good!")

def main():

    convertoOnnx()

if __name__ == "__main__":

    main()
```

**Comment by PINTO0309** [comment]
- `replace_convtasnet.json`
  ```json
  {
    "format_version": 1,
    "operations": [
      {
        "op_name": "/Unsqueeze_4",
        "param_target": "op",
        "new_shape": [2,1,256,24]
      }
    ]
  }
  ```
```bash
onnx2tf \
-i conv_tasnet_dnn.onnx \
-kat input \
-prf replace_convtasnet.json
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/7b10fb1b-24c6-4820-a9b5-0b8585726738)

**Comment by PINTO0309** [comment]
Improved `Unsqueeze` behavior for very limited patterns, so that you don't have to create JSON to do the conversion.

https://github.com/PINTO0309/onnx2tf/releases/tag/1.15.15

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/e731bfe1-4dc0-4074-a0c0-a457c47b7822)

**Comment by ajithvallabai** [comment]
Thanks

**Comment by ajithvallabai** [comment]
@PINTO0309  In the onnx model shared above there was PRelu as there is some problem with prelu in tflite runtime side the onnx output wont match with tflite output even if i use ```-rtpo PReLU```
I replaced prelu with relu in the source model manually and got the onnx and tflite output models 
these are the model link https://drive.google.com/drive/folders/1b7x5x_4QoSH2TLvRwMEjb0JLzSo1mgxc?usp=sharing
Command used to convert onnx to tflite is 
```onnx2tf -i conv_tasnet_dnn_relu.onnx -kat input  -cotof```
The output of onnx doesnt match with tensorflow pb model i think . Is there any reason for it or anyway to match it ? I am not sure why because of normal reshape the output values are changing

<img width="520" alt="unmatch" src="https://github.com/PINTO0309/onnx2tf/assets/8075112/ae0a965c-90f3-4392-b333-ae78a02cb279">

Code used to match onnx and tflite inference : -
[match_tflite_onnx_inference.txt](https://github.com/PINTO0309/onnx2tf/files/12408014/match_tflite_onnx_inference.txt)

**Comment by PINTO0309** [comment]
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/f85458e8-313f-4634-b54e-54ba43e060b5)

**Comment by ajithvallabai** [comment]
Wow thanks could u share the replace_parameter.json

**Comment by PINTO0309** [comment]
```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/Reshape_3",
      "param_target": "inputs",
      "param_name": "/Mul_output_0",
      "pre_process_transpose_perm": [0,1,3,2]
    }
  ]
}
```

**Comment by ajithvallabai** [comment]
thanks a lot

**Comment by ajithvallabai** [comment]
@PINTO0309 really sorry to disturb you again . I just changed the input tensor in first comment from
```dummy_input = torch.ones(2, 1, 2, 250).to(torch.device('cpu'))``` to
```dummy_input = torch.ones(1, 1, 2, 44100).to(torch.device('cpu'))``` and built a onnx model.
i am not able to convert the onnx model to tflite 
Model - https://drive.google.com/file/d/1WEPZ1gB2TCra5501CdiBvVcxSlU4uj5G/view?usp=sharing
Tried both 
```onnx2tf -i conv_tasnet_dnn_r.onnx -kat input  -prf replace_reshape.json -cotof``` and
```onnx2tf -i conv_tasnet_dnn_r.onnx -kat input  -cotof```

```
INFO:  input.1.tensor: name: tf.compat.v1.transpose_365/transpose:0 shape: (1, 1024, 4409) dtype: <dtype: 'float32'> 
INFO:  input.2.shape: val: [1, 4, 256, 4409] 
INFO:  output.1.output: name: tf.reshape_163/Reshape:0 shape: (1, 4, 256, 4409) dtype: <dtype: 'float32'> 

INFO: onnx_op_type: Mul onnx_op_name: /Mul
INFO:  input_name.1: /Unsqueeze_4_output_0 shape: [1, 1, 256, 4409] dtype: float32
INFO:  input_name.2: /separator/Reshape_output_0 shape: [1, 4, 256, 4409] dtype: float32
INFO:  output_name.1: /Mul_output_0 shape: [1, 4, 256, 4409] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/.../anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 282, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/.../anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 355, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/.../anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/.../anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/onnx2tf/ops/Mul.py", line 212, in make_node
    tf.math.multiply(
  File "/home/.../anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/.../anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/cluster34/anaconda3/envs/bytedmss_39/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.math.multiply_643" (type TFOpLambda).

Dimensions must be equal, but are 4409 and 256 for '{{node tf.math.multiply_643/Mul}} = Mul[T=DT_FLOAT](Placeholder, Placeholder_1)' with input shapes: [1,4409,256,1], [1,256,4409,4].

Call arguments received by layer "tf.math.multiply_643" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 4409, 256, 1), dtype=float32)
  • y=tf.Tensor(shape=(1, 256, 4409, 4), dtype=float32)
  • name='/Mul'
```


```
{
    "format_version": 1,
    "operations": [
        {
            "op_name": "/Unsqueeze_4",
            "param_target": "op",
            "new_shape": [1, 1, 4409, 256]
        }
    ]
  }
```
I tried all the combinations [1, 1, 4409, 256], [1,  4409, 1,256], [1, 4409, 256,1], [1, 1,  256,4409], [1, 256,1,  4409],[1,  256,4409,1] but no luck

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.15.16

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/Reshape_3",
      "param_target": "inputs",
      "param_name": "/Mul_output_0",
      "pre_process_transpose_perm": [0,3,1,2]
    }
  ]
}
```
```bash
onnx2tf \
-i conv_tasnet_dnn_r_1_1_2_44100.onnx \
-prf replace.json \
-cotof \
-cotoa 1e-2
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/7a69c83c-c4cc-483c-8185-239b9683b6d5)

**Comment by ajithvallabai** [comment]
thanks
