### ISSUE TITLE
Failed to run test sample

### ISSUE THREAD

**Issue by GanchengZhu** [PINTO0309/onnx2tf#53]
### Issue Type

Others

### onnx2tf version number

1.2.13

### Download URL for ONNX

wget https://github.com/PINTO0309/onnx2tf/releases/download/1.1.27/human_segmentation_pphumanseg_2021oct.onnx

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "StatefulPartitionedCall/Tile_4",
      "param_target": "inputs", # attributes or inputs
      "param_name": "const_fold_opt__677",
      "values": [1,1,17] # Disable parameter transposition or overwrite parameters
    },
    {
      "op_name": "StatefulPartitionedCall/Cast_3",
      "param_target": "attributes", # attributes or inputs
      "param_name": "to",
      "values": 1 # Disable parameter transposition or overwrite "to" parameters
    },
    {
      "op_name": "Resize__697",
      "param_target": "inputs",
      "param_name": "Concat__696:0",
      "values": [26,26] # Replacement of unk__x (Resize OP, sizes height/width parameter)
    },
    {
      "op_name": "Transpose__927",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3] # Disable parameter transposition or overwrite "perm" parameters
    },
    {
      "op_name": "StatefulPartitionedCall/functional_1/max_unpooling2d_2/Reshape_1",
      "param_target": "inputs",
      "param_name": "const_fold_opt__911",
      "values": [4,131072] # Overwrite "shape" parameters
    },
    {
      "op_name": "Reshape_25",
      "param_target": "outputs",
      "param_name": "onnx::InstanceNormalization_270",
      "post_process_transpose_perm": [0,2,1] # Extrapolate 3D Transpose after Reshape
    },
    {
      "op_name": "Reshape_30",
      "param_target": "outputs",
      "param_name": "onnx::Mul_275",
      "post_process_transpose_perm": [0,2,3,1] # Extrapolate 4D Transpose after Reshape
    },
    {
      "op_name": "flatten_1127",
      "param_target": "inputs",
      "param_name": "dropout0",
      "pre_process_transpose_perm": [0,3,1,2]
    }
  ]
}
```

### Description

Failed to run test sample in CLI. Use this:

```
wget https://github.com/PINTO0309/onnx2tf/releases/download/1.1.27/human_segmentation_pphumanseg_2021oct.onnx
wget https://github.com/PINTO0309/onnx2tf/releases/download/1.1.27/replace.json
onnx2tf -i human_segmentation_pphumanseg_2021oct.onnx -prf replace.json
```

Encountered: 

```
Model optimizing started ============================================================
WARNING: Failed to optimize the onnx file.
Traceback (most recent call last):
  File "C:\Users\zhugc\AppData\Roaming\Python\Python39\site-packages\onnx2tf\onnx2tf.py", line 427, in convert
    result = subprocess.check_output(
  File "D:\Anaconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['onnxsim', 'human_segmentation_pphumanseg_2021oct.onnx', 'human_segmentation_pphumanseg_2021oct.onnx']' returned non-zero exit status 1.

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model convertion started ============================================================
INFO: input_op_name: x shape: [1, 3, 192, 192] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "C:\Users\zhugc\AppData\Roaming\Python\Python39\site-packages\onnx2tf\utils\common_functions.py", line 262, in print_wrapper_func
    result = func(*args, **kwargs)
  File "C:\Users\zhugc\AppData\Roaming\Python\Python39\site-packages\onnx2tf\ops\Input.py", line 81, in make_node
    if graph_input.shape != tf.TensorShape(None) and len(graph_input.shape) in [3, 4, 5] \
  File "C:\Users\zhugc\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\tensor_shape.py", line 1294, in __ne__
    raise ValueError("The inequality of unknown TensorShapes is undefined.")
ValueError: The inequality of unknown TensorShapes is undefined.
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC, use the -kt option.
```

**Comment by PINTO0309** [comment]
If you follow the procedure described in the README, you will succeed.

However, if you run the sample under the folder where you git cloned onnx2tf, the `replace.json` file obtained by the wget command should be `replace.json.1` because replace.json already exists in the folder. You should verify that the folder downloaded to you is the correct JSON file.

```bash
$ rm replace.json
$ wget https://github.com/PINTO0309/onnx2tf/releases/download/1.1.27/human_segmentation_pphumanseg_2021oct.onnx
$ wget https://github.com/PINTO0309/onnx2tf/releases/download/1.1.27/replace.json
$ onnx2tf -i human_segmentation_pphumanseg_2021oct.onnx -prf replace.json
```
```
 tf.identity (TFOpLambda)                     (1, 192, 192, 2)               0               ['tf.compat.v1.transpose_1[0][0]']             
                                                                                                                                            
============================================================================================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
____________________________________________________________________________________________________________________________________________

saved_model output started ==========================================================
saved_model output complete!
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
Estimated count of arithmetic ops: 1.164 G  ops, equivalently 0.582 G  MACs
Float32 tflite output complete!
Estimated count of arithmetic ops: 1.164 G  ops, equivalently 0.582 G  MACs
Float16 tflite output complete!
```

Added `rm` command to README.
commit: https://github.com/PINTO0309/onnx2tf/commit/1576d9f4803751adedeb5f907b1322302bc94ceb

**Comment by GanchengZhu** [comment]
I didn't run the sample under the folder 'onnx2tf'. I think different operation systems cause this problem. My device is based on Windows. I can run the example of 'resnet18-v1-7.onnx' successfully.

**Comment by PINTO0309** [comment]
I ask you again, have you opened the json file and checked its contents?

**Comment by PINTO0309** [comment]
If the newline code of the downloaded JSON file is still LF, you may need to convert it to CRLF.

**Comment by PINTO0309** [comment]
I seem to be getting an error message that I have not encountered before, so if your TensorFlow version is newer than v2.10.0 (e.g. v2.11.0), maybe downgrading to TensorFlow v2.10.0 will change things.

It seems that TensorFlow itself is outputting the error, not onnx2tf.
```
  File "C:\Users\zhugc\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\tensor_shape.py", line 1294, in __ne__
    raise ValueError("The inequality of unknown TensorShapes is undefined.")
ValueError: The inequality of unknown TensorShapes is undefined.
```

**Comment by PINTO0309** [comment]
The problem is still caused by the version of TensorFlow in your environment being too old. The following unnecessary logic is present in `tensor_shape.py` at line 1294 until `v2.8.0`. This logic does not exist in TensorFlow v2.10.0.

https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/python/framework/tensor_shape.py#L1287-L1300

- Tensorflow v2.8.0
  ```python
    def __ne__(self, other):
      """Returns True if `self` is known to be different from `other`."""
      try:
        other = as_shape(other)
      except TypeError:
        return NotImplemented
      if self.rank is None or other.rank is None:
        raise ValueError("The inequality of unknown TensorShapes is undefined.")
      if self.rank != other.rank:
        return True
      return self._dims != other.dims
  
  
    def __reduce__(self):
      return TensorShape, (self._dims,)
  ```

Please install the version TensorFlow v2.10.0 as described in the README. Older versions are not supported.

**Comment by GanchengZhu** [comment]
You are really a warm-hearted person.
Thanks very much for your response.

**Comment by GanchengZhu** [comment]
I'm so sorry about my ignoring the README.

**Comment by PINTO0309** [comment]
https://github.com/tensorflow/tensorflow/issues/25442
