### ISSUE TITLE
onnx2tf `download_test_image_data()` S3 file connection error

### ISSUE THREAD

**Issue by glenn-jocher** [PINTO0309/onnx2tf#545]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.17.5

### onnx version number

1.15.0

### onnxruntime version number

1.16.1

### onnxsim (onnx_simplifier) version number

0.4.35

### tensorflow version number

2.13.1

### Download URL for ONNX

Error unrelated to ONNX file

### Parameter Replacement JSON

```json
Error unrelated to JSON file
```

### Description

We are seeing the following error due to S3 connection issues with `download_test_image_data()` not being able to access the *.npy file here:
https://github.com/PINTO0309/onnx2tf/blob/e16bfce440043ed1b28d43c34f7353af70f36b15/onnx2tf/utils/common_functions.py#L4141-L4162

```
TensorFlow SavedModel: running 'onnx2tf -i "path with spaces/yolov8n-seg.onnx" -o "path with spaces/yolov8n-seg_saved_model" -nuo --non_verbose'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/bin/onnx2tf", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/onnx2tf/onnx2tf.py", line 2291, in main
    model = convert(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/onnx2tf/onnx2tf.py", line 881, in convert
    test_data: np.ndarray = download_test_image_data()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 4123, in download_test_image_data
    test_sample_images_npy = requests.get(URL).content
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

I'm experienced with downloading assets in YOLOv8 and I'd recommend hosting this file as a release asset to allow GitHub to cache it regionally best. I've gone ahead and uploaded this to our assets at https://github.com/ultralytics/assets/releases/download/v0.0.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip as a zip file (unzip code below), or you can also upload it as a zip to your own repo assets in https://github.com/PINTO0309/onnx2tf/releases/tag/1.18.14

```python
    with zipfile.ZipFile('path/to/file.zip', 'r') as f:
        f.extractall('path/to/unzip_dir')
```

**Comment by PINTO0309** [comment]
That's why I go to the trouble of placing my resources in external storage in the US Region, even though I live in Asia.
I don't know what causes the error. Btw, I just accessed the URL directly with wget and curl and the file downloaded fine.

I know that operationally `Assets` are very useful. I also know that S3 can be unstable from region to region.

**Comment by glenn-jocher** [comment]
@PINTO0309 yeah it's very strange that the download fails sometimes. I'm in Spain but I assume the CI runs from US servers, and I can download the file myself manually fine also. It will probably clear up again if we wait some time, but I thought the assets might be more stable because we use them for almost everything (including YOLOv8 model and dataset auto-download) and have never really had any issues over the last few years.

**Comment by PINTO0309** [comment]
Port: Wasabi Storage -> GitHub releases
