### ISSUE TITLE
Problem in padding in ConvTranspose when stride is larger than 1

### ISSUE THREAD

**Issue by Hyunseok-Kim0** [PINTO0309/onnx2tf#56]
### Issue Type

Others

### onnx2tf version number

1.2.14

### onnx version number

1.12.0

### tensorflow version number

2.10

### Download URL for ONNX

Please use code below for debugging.
```python
import os
import shutil

import onnxruntime
import tensorflow as tf
import torch
from einops import rearrange
from torch import nn
import numpy as np
from onnx2tf import convert


class dummy_network(nn.Module):

    def __init__(self):
        super(dummy_network, self).__init__()

        # segmentation fault with wrong padding mode
        # self.tconv = torch.nn.ConvTranspose2d(3, 64, (3, 3), stride=3, padding=1)     # case 1: wrong output
        # self.tconv = torch.nn.ConvTranspose2d(3, 64, (4, 4), stride=3, padding=1)     # case 1: wrong output
        self.tconv = torch.nn.ConvTranspose2d(3, 64, (3, 3), stride=2, padding=1)       # case 2: segmentation fault

    def forward(self, x):
        result = self.tconv(x)

        return result


def main():
    os.makedirs("tflite", exist_ok=True)
    model = dummy_network()
    model.eval()

    dummy_name = "dummy_tconv"
    onnx_save_path = f"tflite/{dummy_name}.onnx"
    temp_tflite = "tflite/model_float32.tflite"
    tflite_save_path = f"tflite/{dummy_name}.tflite"

    # y1, x1, y2, x2
    dummy_x = torch.randn(1, 3, 224, 224, dtype=torch.float32)

    torch.onnx.export(model,
                      args=(dummy_x,),
                      f=onnx_save_path,
                      input_names=["x"],
                      output_names=["result"],
                      opset_version=11)

    # get onnx output
    # -----------------------------------------------------------------------------------------------
    onnx_session = onnxruntime.InferenceSession(onnx_save_path, providers=['CPUExecutionProvider'])
    onnx_inputs = dict(x=dummy_x.numpy())
    onnx_outputs = onnx_session.run(None, onnx_inputs)

    convert(onnx_save_path, output_folder_path="tflite")
    shutil.move(temp_tflite, tflite_save_path)

    # get tflite output
    # -----------------------------------------------------------------------------------------------
    tflite_onnx2tf = tf.lite.Interpreter(model_path=tflite_save_path)
    tflite_onnx2tf.allocate_tensors()
    tflite_onnx2tf.set_tensor(tflite_onnx2tf.get_input_details()[0]['index'],
                              rearrange(dummy_x.numpy(), "n c h w -> n h w c"))
    tflite_onnx2tf.invoke()
    tflite_output = [tflite_onnx2tf.get_tensor(i['index']) for i in tflite_onnx2tf.get_output_details()][0]

    np.testing.assert_allclose(rearrange(tflite_output, "n h w c -> n c h w"), onnx_outputs[0], atol=1e-3, rtol=0.5)

    print("convert done")

    return


if __name__ == "__main__":
    main()

```

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Purpose: Personal development

2. What: Converted tflite contains wrong padding mode which occurs wrong output or segmentation fault when stride is larger than 2 and padding is larger than 0.

3. How: https://github.com/PINTO0309/onnx2tf/blob/686fa3d3cf8b2208911f46014f1d74d40516ccd5/onnx2tf/ops/ConvTranspose.py#L103-L109
In ConvTranspose.py line number 105, padding mode is set to `SAME` by comparing input shape and output shape. However, output shape is not same with input shape when stride is not 1.  
With the code in above section, the outputs between onnx and tflite are different. Even worse, sometimes converted tflite failed to invoke due to segmentation fault, for example, when kernel is (3, 3), stride is (2, 2), padding is (1, 1).
By replacing line number 105 with `[int((s * (i - 1) + k - o) / 2) for s, i, k, o in zip(strides, graph_node_input_shape[2:], kernel_shape, graph_node_output_shape[2:])] == pads[1:3]`, the error is gone in some cases. But this is not enough, there should be more lines of code for comparing given padding value and calculated padding value to check padding mode is `SAME` or not.

**Comment by PINTO0309** [comment]
Hmmm. I'm stumped. The implementation is incredibly complicated. :cry:

**Comment by PINTO0309** [comment]
I have added a direct replacement process for `ConvTranspose` to `tf.nn.convXd_transpose`. This is not an essential measure, but by specifying a parameter in the TensorFlow specification, it directly generates a TensorFlow `tf.nn.convXd_transpose` OP, ignoring the automatic transformation process. https://github.com/PINTO0309/onnx2tf/pull/65/commits/464437aec113c92b7b2cc07f9a7c8c3d7658272c

This is an experimental measure and may require a separate re-implementation of the padding process.

![image](https://user-images.githubusercontent.com/33194443/209471123-57adc126-e020-4bc0-b8a5-17fc72569206.png)

```python
# Param replacement - OP replacement
op_rep_params = kwargs.get('op_rep_params', [])
output_shape_ = None
for op_rep_param in op_rep_params:
    if op_rep_param['param_target'] == 'op':
        output_shape_ = op_rep_param.get('output_shape', None)
        strides_ = op_rep_param.get('strides', None)
        padding_ = op_rep_param.get('padding', 'SAME')
        dilations_ = op_rep_param.get('dilations', None)

        if output_shape_ is None or strides_ is None or group > 1:
            print(
                f'{Color.RED}ERROR:{Color.RESET} ' +
                f'When replacing ConvTranspose OP, "filters", "output_shape" and "strides" must be specified in replace.json. ' +
                f'Also, parameter substitution is not supported when group > 1. ' +
                f'Check the specification of tf.nn.convXd_transpose in TensorFlow and specify the appropriate parameters. ' +
                f'https://www.tensorflow.org/api_docs/python/tf/nn/conv1d_transpose or ' +
                f'https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose or ' +
                f'https://www.tensorflow.org/api_docs/python/tf/nn/conv3d_transpose'
            )
            sys.exit(1)

conv_rs = None
if output_shape_ is None:
    convolved = []
    for (input_tensor_split, weight_split) in zip(input_tensor_splits, weight_splits):
        split_conv_output_shape = conv_output_shape[:-1] + [weight_split.shape[spatial_size]]

        conv_rs = conv_func(
            input=input_tensor_split,
            filters=weight_split,
            output_shape=split_conv_output_shape,
            strides=strides,
            padding=pad_mode,
            dilations=dilations,
        )
        convolved.append(conv_rs)

    if group > 1:
        # concatenate in case of grouped convolution
        conv_rs = tf.concat(values=convolved, axis=-1)
else:
    # OP replacement
    conv_rs = conv_func(
        input=input_tensor_splits[0],
        filters=weight_splits[0],
        output_shape=output_shape_,
        strides=strides_,
        padding=padding_,
        dilations=dilations_,
    )
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.2.24

**Comment by ktobah** [comment]
Hi

I have an issue converting a segmentation model and I think it is related to this, so I will just leave a comment here. The error I get:

```
INFO: onnx_op_type: ConvTranspose onnx_op_name: wa/model.23/proto/upsample/ConvTranspose
INFO:  input_name.1: wa/model.23/proto/cv1/act/Mul_output_0 shape: ['batch', 64, 80, 80] dtype: float32
INFO:  input_name.2: model.23.proto.upsample.weight shape: [64, 64, 2, 2] dtype: float32
INFO:  input_name.3: model.23.proto.upsample.bias shape: [64] dtype: float32
INFO:  output_name.1: wa/model.23/proto/upsample/ConvTranspose_output_0 shape: ['batch', 64, 160, 160] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 313, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 386, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 56, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/ConvTranspose.py", line 288, in make_node
    raise ex1
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/ConvTranspose.py", line 245, in make_node
    conv_rs = conv_func(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling layer "tf.nn.conv2d_transpose" (type TFOpLambda).

Expected int32 passed to parameter 'input_sizes' of op 'Conv2DBackpropInput', got ['batch', 160, 160, 64] of type 'list' instead. Error: Expected int32, but got batch of type 'str'.

Call arguments received by layer "tf.nn.conv2d_transpose" (type TFOpLambda):
  • input=tf.Tensor(shape=(None, 80, 80, 64), dtype=float32)
  • filters=tf.Tensor(shape=(2, 2, 64, 64), dtype=float32)
  • output_shape=["'batch'", '160', '160', '64']
  • strides=['2', '2']
  • padding='VALID'
  • data_format=NHWC
  • dilations=['1', '1']
  • name=None

ERROR: input_onnx_file_path: yolo11n-seg.onnx
ERROR: onnx_op_name: wa/model.23/proto/upsample/ConvTranspose
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

![Image](https://github.com/user-attachments/assets/571a0781-9e45-4f97-bffc-59ed3bc03c7f)

It seems related to the dynamic batch size. The model is [here](https://drive.google.com/file/d/1h3nSMS3NukkZivDv__TGufwqOILWKJfs/view?usp=sharing).

I would appreciate any hints.
