### ISSUE TITLE
Failed to convert Real-ESRGAN x4-general (NCHW)

### ISSUE THREAD

**Issue by md-rifatkhan** [PINTO0309/onnx2tf#563]
### Issue Type

Others

### OS

Others

### onnx2tf version number

1.19.4

### onnx version number

1.15.0

### onnxruntime version number

1.16.3

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.15.0

### Download URL for ONNX

https://github.com/md-rifatkhan/real-esrgan-model/blob/main/fp32.onnx

### Parameter Replacement JSON

```json
??
```

### Description

I've tried to convert with command !onnx2tf -i /content/fp32.onnx -ois data:1,3,512,512  but got : 

```
ValueError: Cannot convert a partially known TensorShape (None, None) to a Tensor.

ERROR: input_onnx_file_path: /content/fp32.onnx
ERROR: onnx_op_name: /Resize
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

```
Full error: Model optimizing started ============================================================
Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃              ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add          │ 1              │ 1                │
│ Constant     │ 102            │ 102              │
│ Conv         │ 34             │ 34               │
│ DepthToSpace │ 1              │ 1                │
│ PRelu        │ 33             │ 33               │
│ Resize       │ 1              │ 1                │
│ Model Size   │ 4.6MiB         │ 4.6MiB           │
└──────────────┴────────────────┴──────────────────┘

Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃              ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add          │ 1              │ 1                │
│ Constant     │ 102            │ 102              │
│ Conv         │ 34             │ 34               │
│ DepthToSpace │ 1              │ 1                │
│ PRelu        │ 33             │ 33               │
│ Resize       │ 1              │ 1                │
│ Model Size   │ 4.6MiB         │ 4.6MiB           │
└──────────────┴────────────────┴──────────────────┘

Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃              ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add          │ 1              │ 1                │
│ Constant     │ 102            │ 102              │
│ Conv         │ 34             │ 34               │
│ DepthToSpace │ 1              │ 1                │
│ PRelu        │ 33             │ 33               │
│ Resize       │ 1              │ 1                │
│ Model Size   │ 4.6MiB         │ 4.6MiB           │
└──────────────┴────────────────┴──────────────────┘

Model optimizing complete!

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
INFO: input_op_name: input shape: ['batch_size', 3, 'height', 'width'] dtype: float32

INFO: 2 / 71
INFO: onnx_op_type: Conv onnx_op_name: /body.0/Conv
INFO:  input_name.1: input shape: ['batch_size', 3, 'height', 'width'] dtype: float32
INFO:  input_name.2: body.0.weight shape: [64, 3, 3, 3] dtype: float32
INFO:  input_name.3: body.0.bias shape: [64] dtype: float32
INFO:  output_name.1: /body.0/Conv_output_0 shape: ['batch_size', 64, 'unk__0', 'unk__1'] dtype: float32
INFO: tf_op_type: convolution_v2
INFO:  input.1.input: name: tf.compat.v1.pad/Pad:0 shape: (None, None, None, 3) dtype: <dtype: 'float32'> 
INFO:  input.2.weights: shape: (3, 3, 3, 64) dtype: <dtype: 'float32'> 
INFO:  input.3.bias: shape: (64,) dtype: <dtype: 'float32'> 
INFO:  input.4.strides: val: [1, 1] 
INFO:  input.5.dilations: val: [1, 1] 
INFO:  input.6.padding: val: VALID 
INFO:  input.7.group: val: 1 
INFO:  output.1.output: name: tf.math.add/Add:0 shape: (None, None, None, 64) dtype: <dtype: 'float32'> 

INFO: 3 / 71
INFO: onnx_op_type: Resize onnx_op_name: /Resize
INFO:  input_name.1: input shape: ['batch_size', 3, 'height', 'width'] dtype: float32
INFO:  input_name.2:  shape: None dtype: None
INFO:  input_name.3: /Constant_output_0 shape: [4] dtype: float32
INFO:  output_name.1: /Resize_output_0 shape: ['unk__70', 3, 'unk__71', 'unk__72'] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 310, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 383, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 53, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Resize.py", line 269, in make_node
    h_w_scale * tf.cast(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 357, in _tensor_shape_tensor_conversion_function
    raise ValueError(
ValueError: Cannot convert a partially known TensorShape (None, None) to a Tensor.

ERROR: input_onnx_file_path: /content/fp32.onnx
ERROR: onnx_op_name: /Resize
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

```

**Comment by PINTO0309** [comment]
This pull request solves the error that occurs only when there are multiple undefined dimensions and `Resize` is specified to be resized by the `scale` parameter. 

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/08d579b4-2790-4899-b141-c0570b3eb28e)

Unfortunately, the last `CRD` mode of `DepthToSpace` is technically difficult to convert to TensorFlow operations unless the tensor shape can be identified.

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/4ed1f39f-a27d-4f58-ba0f-897a55461dfd)

The only way to deal with this vexing problem is to convert the input tensor to a fixed shape at this time.

```
onnx2tf -i fp32.onnx -ois input:1,3,240,320
```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/4f7e23fc-c34a-4b96-8693-82b847f9c737)

**Comment by PINTO0309** [comment]
Fix: https://github.com/PINTO0309/onnx2tf/releases/tag/1.25.2
