### ISSUE TITLE
ONNX Split operation converts to a tf StridedSlice operation with outputs in the wrong order.

### ISSUE THREAD

**Issue by Sowee0** [PINTO0309/onnx2tf#588]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.19.11

### onnx version number

1.15.0

### onnxruntime version number

1.16.3

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.15.0

### Download URL for ONNX

[topformer_small_512x512_160k_2x8_ade20k_512in.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/14542513/topformer_small_512x512_160k_2x8_ade20k_512in.onnx.zip)

### Parameter Replacement JSON

```json
Not used at this time.
```

### Description

1. Research. This fix would remove a block, allowing me to develop models further based on the original TopFormer.
2. The model currently used is a version of the TopFormer model directly converted from the original repository into ONNX. Upon converting the ONNX to TF, the tool raises an error after the Split operation that is converted to a StridedSlice operation. The order of the outputs however is wrong, which breaks the next operation.

The wrong result can already be observed on the op's conversion info, where the tf_op results are out of order:

```
INFO: 150 / 184
INFO: onnx_op_type: Split onnx_op_name: /backbone/Split
INFO:  input_name.1: /backbone/trans/transformer_blocks.3/Add_1_output_0 shape: [1, 296, 8, 8] dtype: float32
INFO:  input_name.2: onnx::Split_626 shape: [4] dtype: int64
INFO:  output_name.1: /backbone/Split_output_0 shape: [1, 24, 8, 8] dtype: float32
INFO:  output_name.2: /backbone/Split_output_1 shape: [1, 48, 8, 8] dtype: float32
INFO:  output_name.3: /backbone/Split_output_2 shape: [1, 96, 8, 8] dtype: float32
INFO:  output_name.4: /backbone/Split_output_3 shape: [1, 128, 8, 8] dtype: float32
INFO: tf_op_type: split
INFO:  input.1.value: name: tf.math.add_88/Add:0 shape: (1, 8, 8, 296) dtype: <dtype: 'float32'> 
INFO:  input.2.num_or_size_splits: shape: (4,) dtype: int64 
INFO:  input.3.axis: val: 3 
INFO:  input.4.num: 
INFO:  output.1.output0: name: tf.strided_slice/StridedSlice:0 shape: (1, 8, 8, 24) dtype: <dtype: 'float32'> 
INFO:  output.2.output1: name: tf.strided_slice_1/StridedSlice:0 shape: (1, 8, 8, 96) dtype: <dtype: 'float32'> 
INFO:  output.3.output2: name: tf.strided_slice_2/StridedSlice:0 shape: (1, 8, 8, 128) dtype: <dtype: 'float32'> 
INFO:  output.4.output3: name: tf.strided_slice_3/StridedSlice:0 shape: (1, 8, 8, 48) dtype: <dtype: 'float32'> 
```

The following op shows the ONNX supposedly right shape ([1,48,8,8]) and the tf_op shows that it was actually incorrect received ([1,8,8,96], without reordering the channels), but somehow manages not to break the code, probably due to casting.

```
INFO: 151 / 184
INFO: onnx_op_type: Conv onnx_op_name: /backbone/SIM.1/global_act/conv/Conv
INFO:  input_name.1: /backbone/Split_output_1 shape: [1, 48, 8, 8] dtype: float32
INFO:  input_name.2: onnx::Conv_931 shape: [192, 48, 1, 1] dtype: float32
INFO:  input_name.3: onnx::Conv_932 shape: [192] dtype: float32
INFO:  output_name.1: /backbone/SIM.1/global_act/conv/Conv_output_0 shape: [1, 192, 8, 8] dtype: float32
INFO: tf_op_type: convolution_v2
INFO:  input.1.input: name: tf.strided_slice_1/StridedSlice:0 shape: (1, 8, 8, 96) dtype: <dtype: 'float32'> 
INFO:  input.2.weights: shape: (1, 1, 48, 192) dtype: <dtype: 'float32'> 
INFO:  input.3.bias: shape: (192,) dtype: <dtype: 'float32'> 
INFO:  input.4.strides: val: [1, 1] 
INFO:  input.5.dilations: val: [1, 1] 
INFO:  input.6.padding: val: SAME 
INFO:  input.7.group: val: 1 
INFO:  output.1.output: name: tf.math.add_89/Add:0 shape: (1, 8, 8, 192) dtype: <dtype: 'float32'> 
```

The following op however can't continue due to a mismatch (the right dims should be [1,8,8,96], but it received the [1,8,8,128] input instead) and the conversion stops.

```
INFO: 153 / 184
INFO: onnx_op_type: Conv onnx_op_name: /backbone/SIM.2/global_act/conv/Conv
INFO:  input_name.1: /backbone/Split_output_2 shape: [1, 96, 8, 8] dtype: float32
INFO:  input_name.2: onnx::Conv_940 shape: [192, 96, 1, 1] dtype: float32
INFO:  input_name.3: onnx::Conv_941 shape: [192] dtype: float32
INFO:  output_name.1: /backbone/SIM.2/global_act/conv/Conv_output_0 shape: [1, 192, 8, 8] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 310, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 383, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Conv.py", line 453, in make_node
    conv_bias(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Conv.py", line 302, in conv_bias
    tf.nn.convolution(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.nn.convolution_49" (type TFOpLambda).

Depth of input (128) is not a multiple of input depth of filter (96) for '{{node tf.nn.convolution_49/convolution}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Placeholder, tf.nn.convolution_49/convolution/filter)' with input shapes: [1,8,8,128], [1,1,96,192].

Call arguments received by layer "tf.nn.convolution_49" (type TFOpLambda):
  • input=tf.Tensor(shape=(1, 8, 8, 128), dtype=float32)
  • filters=tf.Tensor(shape=(1, 1, 96, 192), dtype=float32)
  • strides=['1', '1']
  • padding='SAME'
  • data_format=None
  • dilations=['1', '1']
  • name=None

ERROR: input_onnx_file_path: /content/topformer_small_512x512_160k_2x8_ade20k_512in.onnx
ERROR: onnx_op_name: /backbone/SIM.2/global_act/conv/Conv
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```
3. I tried using the operation replacement json to swap the inputs around but later realized conv is not a supported operation as stated in the readme. Looking at Gorordo's repo and using their ONNX conversion of the TopFormer model doesn't show this slicing problem.

4. This problem solved would allow me to use the topformer for mobile inference and generate new models based on it.
5.  - https://github.com/ibaiGorordo/ONNX-TopFormer-Semantic-Segmentation
     - https://github.com/hustvl/TopFormer

**Comment by PINTO0309** [comment]
Sorry for the late reply. I was away the day you posted the issue and could not respond immediately. There was a bug in `Split`'s handling of irregular tensor splitting by a constant list, which has now been fixed and is being tested.

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/70355887-dbef-4de2-a05d-633260d0a4bb)

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.19.15
