### ISSUE TITLE
issue converting clip onnx float model to tflite

### ISSUE THREAD

**Issue by tensorbuffer** [PINTO0309/onnx2tf#721]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

1.26.2

### onnx version number

1.16.1

### onnxruntime version number

1.18.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.17.0

### Download URL for ONNX

https://huggingface.co/mlunar/clip-variants/resolve/main/models/clip-resnet-50x16-visual-float32.onnx?download=true

### Parameter Replacement JSON

```json
None used
```

### Description

1. Purpose:
Convert the CLIP float model to tflite
2. What:
$ docker run --rm -it -v `pwd`:/workdir -w /workdir docker.io/pinto0309/onnx2tf:1.26.2
user@b517e42c27c7:/workdir$ onnx2tf -i clip-resnet-50x16-visual-float32.onnx
INFO: 323 / 422
INFO: onnx_op_type: Concat onnx_op_name: Concat_321
INFO:  input_name.1: onnx____Concat_1218 shape: None dtype: None
INFO:  input_name.2: onnx____Concat_1219 shape: None dtype: None
INFO:  output_name.1: onnx____Reshape_1220 shape: None dtype: None
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Concat.py", line 282, in make_node
    tf.concat(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling layer "tf.concat_1" (type TFOpLambda).

Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, int64] that don't all match.

Call arguments received by layer "tf.concat_1" (type TFOpLambda):
  • values=['tf.Tensor(shape=(2,), dtype=int32)', 'tf.Tensor(shape=(1,), dtype=int64)']
  • axis=0
  • name='Concat_321'

ERROR: input_onnx_file_path: clip-resnet-50x16-visual-float32.onnx
ERROR: onnx_op_name: Concat_321
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

**Comment by PINTO0309** [comment]
```bash
onnx2tf \
-i clip-resnet-50x16-visual-float32.onnx \
-cotof \
-ois input:1,3,384,384
```
![image](https://github.com/user-attachments/assets/be852a97-30e7-4713-9ebd-ae753947ff2a)

**Comment by tensorbuffer** [comment]
@PINTO0309 Hi I tried your commands and it's the same result. Are you using the latest 1.26.2 docker image?
user@646ed618ae02:/workdir$ onnx2tf -i clip-resnet-50x16-visual-float32.onnx -cotof -ois input:1,3,384,384 -v debug
...
INFO: 323 / 422
INFO: onnx_op_type: Concat onnx_op_name: Concat_321
INFO:  input_name.1: onnx____Concat_1218 shape: None dtype: None
INFO:  input_name.2: onnx____Concat_1219 shape: None dtype: None
INFO:  output_name.1: onnx____Reshape_1220 shape: None dtype: None
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Concat.py", line 282, in make_node
    tf.concat(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling layer "tf.concat_1" (type TFOpLambda).

Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, int64] that don't all match.

Call arguments received by layer "tf.concat_1" (type TFOpLambda):
  • values=['tf.Tensor(shape=(2,), dtype=int32)', 'tf.Tensor(shape=(1,), dtype=int64)']
  • axis=0
  • name='Concat_321'

**Comment by PINTO0309** [comment]
```bash
docker run --rm -it \
-v `pwd`:/workdir \
-w /workdir \
docker.io/pinto0309/onnx2tf:1.26.2

rm clip-resnet-50x16-visual-float32.onnx

curl -L -O https://huggingface.co/mlunar/clip-variants/resolve/main/models/clip-resnet-50x16-visual-float32.onnx

onnx2tf \
-i clip-resnet-50x16-visual-float32.onnx \
-cotof \
-ois input:1,3,384,384
```
![image](https://github.com/user-attachments/assets/4936221d-6733-4ff3-b01a-ebd1bf59cec6)

**Comment by tensorbuffer** [comment]
Hi @PINTO0309 
I am able to repro your steps and result, however I noticed that this only works if the model file is able to be modified by onnx2tf (e.g. I have to add "sudo chmod 777 clip-resnet-50x16-visual-float32.onnx"). Comparing the sha1sum of the onnx model, it changed before and after onnx2tf. So onnx2tf modifies the onnx model?

**Comment by PINTO0309** [comment]
https://github.com/daquexian/onnx-simplifier
